export { Confetti } from "./confetti"
export { SuccessOverlay } from "./success-overlay"
export { renderContent } from "./render-content"
export { lessonsData, bilingualLessons } from "./lesson-registry"
export type { LessonStep, Chapter, LessonData } from "./types"
export { StepRenderer } from "./step-renderer"
export { ExplainStep } from "./explain-step"
export { TryItStep } from "./tryit-step"
export { QuizStep } from "./quiz-step"
export { InteractiveStep } from "./interactive-step"
export { AnimationStep } from "./animation-step"
export { InteractiveRenderer, AnimationRenderer } from "./interactive-renderer"
export { default as componentRegistry } from "./component-registry"
