/**
 * Quest curated metadata — Phase 2 of redesign.
 *
 * Layered on top of ALL_PROBLEMS (in app/quest/[problemId]/data.ts),
 * which holds id/title/source/URL. This file adds the *pedagogical*
 * metadata that the curriculum graph and admin dashboard read:
 *
 *   - type:                template family this quest fits
 *   - concepts_taught:     concepts a student learns by completing it
 *   - concepts_required:   concepts that should be known beforehand
 *   - difficulty:          1 (easiest) — 5 (hardest), within Bronze
 *   - supported_languages: which solutions are verified to work
 *
 * Quests without an explicit entry fall back to DEFAULT_META — the
 * loader never throws, so we can fill in entries gradually as we
 * audit each quest. Adding/changing entries here is purely additive
 * and never affects student data.
 */

export type QuestTemplateType =
  | "brute-force"        // try all options; learn the search loop
  | "pattern-discovery"  // first idea fails; refine; correct formula
  | "algorithm-reveal"   // build up to the key insight + apply
  | "simulation";        // step-by-step trace of given rules

export type SupportedLang = "py" | "cpp";

/**
 * Release stage — Phase 5 of redesign.
 *
 * Lets us roll out major rewrites in 3 phases without surprising
 * existing students:
 *   - "internal": only teachers see it in the catalog. Students with
 *                 a direct URL still load (we just show a banner).
 *   - "beta":    visible to students who opted in via the
 *                "베타 quest 시도" toggle (useReleasePref).
 *   - "full":    visible to everyone (default — equivalent to old
 *                behavior).
 *
 * Default = "full" so adding the field is purely additive and never
 * hides an existing quest from students.
 */
export type ReleaseStage = "internal" | "beta" | "full";

export interface QuestConceptMeta {
  type: QuestTemplateType;
  concepts_taught: string[];
  concepts_required: string[];
  /** 1 (easiest) .. 5 (hardest), Bronze-relative. */
  difficulty: 1 | 2 | 3 | 4 | 5;
  /** Which languages have a verified, runnable solution. */
  supported_languages: SupportedLang[];
  /** Default "full" — see ReleaseStage. */
  release_stage?: ReleaseStage;
  /**
   * Phase 1: input/expected pairs for CI verification.
   *
   * When both `validate_io` and `solution_py` are set, the
   * `validate-solutions` script runs the Python solution with each
   * input on stdin and compares stdout (after rstrip) to expected.
   * Mismatches are reported as failures. Quests without both fields
   * are skipped — no harm to existing flow.
   */
  validate_io?: { input: string; expected: string }[];
  /**
   * Canonical Python reference solution. Kept small (Bronze-class)
   * so it can live alongside the meta entry. Not shown to students;
   * only used by CI. The visible solutions in App.jsx may use
   * different syntax for pedagogical clarity.
   */
  solution_py?: string;
}

const DEFAULT_META: QuestConceptMeta = {
  type: "simulation",
  concepts_taught: [],
  concepts_required: [],
  difficulty: 2,
  supported_languages: ["py", "cpp"],
  release_stage: "full",
};

/**
 * Concept ontology (registry of all valid concept tags).
 * Every concept used in QUEST_CONCEPT_META must be listed here.
 * The curriculum graph reads this to build the prereq DAG.
 *
 * Categories are lightweight grouping for the dashboard view —
 * not strict — concepts can be referenced cross-category.
 */
export const CONCEPT_ONTOLOGY = {
  // Foundation
  "loop": "for/while basics",
  "function-basics": "def / function definition",
  "recursion": "function calls itself",
  "list-basics": "Python list / C++ vector creation + push_back",
  "vector-basics": "C++ vector creation + push_back",
  "string-basics": "string indexing, length",
  "dict-basics": "Python dict / C++ map (cpp-16 only)",
  "set-basics": "Python set / C++ set for dedup membership",
  "math-basics": "+, -, *, %, abs",
  "io-basics": "input + output",

  // Counting & lookups
  "frequency-count": "Counter / freq map of array values",
  "peak-max-constraint": "constraint that one value must exceed others",
  "two-pointer": "left + right pointer scan",
  "prefix-sum": "running totals for range queries",
  "diff-array": "difference array trick",
  "sliding-window": "moving window sum / count",

  // Search
  "linear-search": "scan to find first/last match",
  "nested-loop-search": "double loop over (i, j)",
  "binary-search": "halving search on sorted data",
  "fix-middle": "fix one variable, optimize the others",
  "ternary-search": "unimodal search",

  // Sorting
  "sort-basics": "sort an array, then process",
  "custom-comparator": "sort by a custom key",
  "stable-sort": "preserve order of equal elements",

  // Combinatorics
  "permutation-enum": "enumerate all permutations of 1..N",
  "subset-enum": "enumerate all subsets of N items",
  "combination-count": "C(N, k) counting",
  "tuple-enum": "iterate over all 2-tuples / 3-tuples",

  // Strings
  "string-indexing": "char-by-char access with []",
  "string-search": "substring / pattern search",
  "char-counting": "letter frequency",

  // Game theory / brute force
  "exhaustive-pair": "try every pair (a, b) and check a property",
  "dismantle-rule": "Nhoj's deletion process (Open 2024 Bronze)",
  "game-theory-parity": "win/lose by parity",

  // Geometry / grid
  "grid-2d": "row × col grid traversal",
  "bounding-box": "min/max coords of points",
  "rectangle-overlap": "intersection / union of rectangles",
  "rotation": "rotate matrix or array",

  // Greedy / simulation
  "greedy-pick": "always take locally-best option",
  "event-sweep": "process events in time order",
  "simulation-step": "step through given rules until done",
  "interval-merge": "merge overlapping intervals",

  // Graph / state (for Silver+)
  "bfs-grid": "BFS on grid",
  "graph-component": "find connected components",
  "topological-order": "topological sort",
  "tree-traversal": "DFS through tree edges",
} as const;

export type ConceptId = keyof typeof CONCEPT_ONTOLOGY;

/**
 * Curated entries — fill in as we audit quests. Quests without an
 * entry use DEFAULT_META.
 */
export const QUEST_CONCEPT_META: Record<string, QuestConceptMeta> = {
  // ─── Deeply audited 4 (Phase 0/1 of content review) ──────────
  cowphotos: {
    type: "pattern-discovery",
    concepts_taught: ["frequency-count", "peak-max-constraint"],
    concepts_required: ["loop", "vector-basics"],
    difficulty: 2,
    supported_languages: ["py", "cpp"],
    // Phase 1: deferred CI runner — verified vs USACO Open 2025 Bronze #2.
    // Case 1 is the literal USACO sample (T=2). Case 2 is an extra
    // stress case with peak-freq > 1 (the formula's tricky branch).
    validate_io: [
      {
        input: "2\n4\n1 1 2 3\n4\n3 3 2 1\n",
        expected: "3\n1",
      },
      {
        input: "1\n5\n4 4 3 3 2\n",
        expected: "3",
      },
    ],
    // Fast I/O + Counter — O(N) per case (sum N ≤ 10⁶).
    // Earlier `h.count(v)` was O(N) per distinct value → O(N²) per case → TLE.
    solution_py: [
      "import sys",
      "from collections import Counter",
      "",
      "data = sys.stdin.buffer.read().split()",
      "idx = 0",
      "T = int(data[idx]); idx += 1",
      "for _ in range(T):",
      "    N = int(data[idx]); idx += 1",
      "    h = data[idx:idx+N]; idx += N",
      "    cnt = Counter(h)",
      "    M = max(cnt, key=int)",
      "    rings = sum(1 for v, c in cnt.items() if int(v) < int(M) and c >= 2)",
      "    print(2 * rings + 1)",
    ].join("\n"),
  },
  hps: {
    type: "brute-force",
    concepts_taught: ["exhaustive-pair", "string-indexing"],
    concepts_required: ["loop", "string-basics", "vector-basics"],
    difficulty: 2,
    supported_languages: ["py", "cpp"],
    // Phase 1: deferred CI runner — verified vs USACO Open 2025 Bronze #1.
    validate_io: [{
      input: "3 3\nD\nWD\nLWD\n1 2\n2 3\n1 1\n",
      expected: "0\n0\n5",
    }],
    solution_py: [
      "N, M = map(int, input().split())",
      "beats = [[False] * N for _ in range(N)]",
      "for i in range(N):",
      "    row = input().strip()",
      "    for j in range(i + 1):",
      "        if row[j] == 'W':",
      "            beats[i][j] = True",
      "        elif row[j] == 'L':",
      "            beats[j][i] = True",
      "for _ in range(M):",
      "    s1, s2 = map(int, input().split())",
      "    s1 -= 1",
      "    s2 -= 1",
      "    # Count cards that beat BOTH Elsie cards (the 'dominators')",
      "    dom = 0",
      "    for c in range(N):",
      "        if beats[c][s1] and beats[c][s2]:",
      "            dom += 1",
      "    # Bessie hands with at least one dominator: N^2 - (N - dom)^2",
      "    print(N * N - (N - dom) * (N - dom))",
    ].join("\n"),
  },
  mooin3: {
    type: "brute-force",
    concepts_taught: ["nested-loop-search", "fix-middle"],
    concepts_required: ["loop", "string-basics"],
    difficulty: 3,
    supported_languages: ["py", "cpp"],
    // Verified against USACO 2025 Open Bronze #3 official sample.
    validate_io: [
      {
        input: "12 5\nabcabbacabac\n1 12\n2 7\n4 8\n2 5\n3 10\n",
        expected: "28\n6\n1\n-1\n12",
      },
    ],
    // Full-credit solution: per-character precompute (first_diff, last_same)
    // + position lists; per query iterate 26 chars and pick best j near
    // midpoint. O(26·N + Q·26·log N).
    // Iterate-by-j is O(Q·N) — TLE in Python at full N=10⁵, Q=3·10⁴.
    // Smarter: for each character c, find the BEST j on positions[c] near
    // the midpoint of (i_c, k_c). f(j) = (j−i)(k−j) is a downward
    // parabola peaking at (i+k)/2, so the optimum j is whichever
    // position[c] entry is closest to that midpoint. O(Q · 26 · log N).
    solution_py: [
      "import sys",
      "",
      "def find_first_at_least(sorted_arr, target, lo, hi):",
      "    while lo < hi:",
      "        mid = (lo + hi) // 2",
      "        if sorted_arr[mid] < target: lo = mid + 1",
      "        else: hi = mid",
      "    return lo",
      "",
      "def find_first_greater_than(sorted_arr, target, lo, hi):",
      "    while lo < hi:",
      "        mid = (lo + hi) // 2",
      "        if sorted_arr[mid] <= target: lo = mid + 1",
      "        else: hi = mid",
      "    return lo",
      "",
      "data = sys.stdin.buffer.read().split()",
      "p = 0",
      "N = int(data[p]); p += 1",
      "Q = int(data[p]); p += 1",
      "s = data[p].decode(); p += 1",
      "",
      "positions_of = [[] for _ in range(26)]",
      "for idx in range(N):",
      "    positions_of[ord(s[idx]) - 97].append(idx)",
      "",
      "INF = N",
      "nearest_diff = [[INF] * (N + 1) for _ in range(26)]",
      "latest_same  = [[-1]  * (N + 1) for _ in range(26)]",
      "for c in range(26):",
      "    ch = chr(c + 97)",
      "    next_diff_idx = INF",
      "    for idx in range(N - 1, -1, -1):",
      "        if s[idx] != ch: next_diff_idx = idx",
      "        nearest_diff[c][idx] = next_diff_idx",
      "    last_same_idx = -1",
      "    for idx in range(N):",
      "        if s[idx] == ch: last_same_idx = idx",
      "        latest_same[c][idx] = last_same_idx",
      "",
      "for _ in range(Q):",
      "    l = int(data[p]) - 1; p += 1",
      "    r = int(data[p]) - 1; p += 1",
      "    best = -1",
      "    for c in range(26):",
      "        left_i = nearest_diff[c][l]",
      "        if left_i >= r: continue",
      "        right_k = latest_same[c][r]",
      "        if right_k <= left_i: continue",
      "        c_positions = positions_of[c]",
      "        n_positions = len(c_positions)",
      "        first_valid = find_first_greater_than(c_positions, left_i, 0, n_positions)",
      "        first_invalid = find_first_at_least(c_positions, right_k, 0, n_positions)",
      "        if first_valid >= first_invalid: continue",
      "        j_peak = (left_i + right_k) // 2",
      "        peak_idx = find_first_at_least(c_positions, j_peak, first_valid, first_invalid)",
      "        for cand_idx in (peak_idx, peak_idx - 1):",
      "            if first_valid <= cand_idx < first_invalid:",
      "                j = c_positions[cand_idx]",
      "                product = (j - left_i) * (right_k - j)",
      "                if product > best: best = product",
      "    print(best)",
    ].join("\n"),
  },
  rounding: {
    type: "brute-force",
    concepts_taught: ["digit-dp", "rounding-rules", "case-analysis"],
    concepts_required: ["loop", "function-basics"],
    difficulty: 4,
    supported_languages: ["py", "cpp"],
    validate_io: [
      { input: "4\n1\n100\n4567\n3366\n", expected: "0\n5\n183\n60" },
    ],
    // Smart: per-P leading-4 enumeration with digit DP for partial range.
    solution_py: [
      "import sys",
      "from functools import lru_cache",
      "",
      "def main():",
      "    data = sys.stdin.buffer.read().split()",
      "    T = int(data[0])",
      "    GC = [0]",
      "    for k in range(1, 12):",
      "        GC.append(GC[-1] * 10 + 5)",
      "    for t in range(1, T + 1):",
      "        N = int(data[t])",
      "        ans = 0",
      "        if N >= 10:",
      "            P = 2",
      "            while 10**(P-1) <= N:",
      "                lo = 4 * 10**(P-1)",
      "                hi_full = 5 * 10**(P-1) - 1",
      "                if N >= lo:",
      "                    if N >= hi_full:",
      "                        ans += GC[P-1]",
      "                    else:",
      "                        M = N - lo",
      "                        k = P - 1",
      "                        digits = [(M // 10**(k-1-i)) % 10 for i in range(k)]",
      "                        @lru_cache(maxsize=None)",
      "                        def f(pos, tight, q):",
      "                            if pos == k:",
      "                                return 1 if q == 1 else 0",
      "                            max_d = digits[pos] if tight else 9",
      "                            r = 0",
      "                            for d in range(max_d + 1):",
      "                                nt = tight and (d == max_d)",
      "                                if q == 0:",
      "                                    nq = 0 if d == 4 else (1 if d >= 5 else 2)",
      "                                else:",
      "                                    nq = q",
      "                                r += f(pos + 1, nt, nq)",
      "                            return r",
      "                        ans += f(0, True, 0)",
      "                        f.cache_clear()",
      "                P += 1",
      "        print(ans)",
      "",
      "main()",
    ].join("\n"),
  },
  cheese: {
    type: "brute-force",
    concepts_taught: ["3d-grid", "incremental-update", "axis-row-counting"],
    concepts_required: ["loop", "list-basics", "2d-list"],
    difficulty: 3,
    supported_languages: ["py", "cpp"],
    validate_io: [
      { input: "2 5\n0 0 0\n1 1 1\n0 1 0\n1 0 0\n1 1 0\n", expected: "0\n0\n1\n2\n5" },
    ],
    solution_py: [
      "import sys",
      "",
      "data = sys.stdin.buffer.read().split()",
      "p = 0",
      "N = int(data[p]); p += 1",
      "Q = int(data[p]); p += 1",
      "cz = [[0]*N for _ in range(N)]",
      "cy = [[0]*N for _ in range(N)]",
      "cx = [[0]*N for _ in range(N)]",
      "carved = set()",
      "valid = 0",
      "for _ in range(Q):",
      "    x = int(data[p]); p += 1",
      "    y = int(data[p]); p += 1",
      "    z = int(data[p]); p += 1",
      "    if (x, y, z) in carved:",
      "        print(valid); continue",
      "    carved.add((x, y, z))",
      "    cz[x][y] += 1",
      "    if cz[x][y] == N: valid += 1",
      "    cy[x][z] += 1",
      "    if cy[x][z] == N: valid += 1",
      "    cx[y][z] += 1",
      "    if cx[y][z] == N: valid += 1",
      "    print(valid)",
    ].join("\n"),
  },
  moo: {
    type: "brute-force",
    concepts_taught: ["string-search", "delta-update", "single-edit-search"],
    concepts_required: ["loop", "string-basics"],
    difficulty: 4,
    supported_languages: ["py", "cpp"],
    validate_io: [
      { input: "10 2\nzzmoozzmoo\n", expected: "1\nmoo" },
      { input: "17 2\nmomoobaaaaaqqqcqq\n", expected: "3\naqq\nbaa\ncqq" },
    ],
    solution_py: [
      "import sys",
      "",
      "data = sys.stdin.buffer.read().split()",
      "N = int(data[0])",
      "F = int(data[1])",
      "s = data[2].decode()",
      "",
      "cnt = {}",
      "for i in range(N - 2):",
      "    sub = s[i:i+3]",
      "    if sub[1] == sub[2] and sub[0] != sub[1]:",
      "        cnt[sub] = cnt.get(sub, 0) + 1",
      "",
      "answer = set()",
      "for m, c in cnt.items():",
      "    if c >= F:",
      "        answer.add(m)",
      "",
      "for i in range(N):",
      "    old_c = s[i]",
      "    for nc in 'abcdefghijklmnopqrstuvwxyz':",
      "        if nc == old_c: continue",
      "        delta = {}",
      "        j_lo = max(0, i - 2)",
      "        j_hi = min(N - 3, i)",
      "        for j in range(j_lo, j_hi + 1):",
      "            old_sub = s[j:j+3]",
      "            new_chars = list(old_sub)",
      "            new_chars[i - j] = nc",
      "            new_sub = ''.join(new_chars)",
      "            if old_sub[1] == old_sub[2] and old_sub[0] != old_sub[1]:",
      "                delta[old_sub] = delta.get(old_sub, 0) - 1",
      "            if new_sub[1] == new_sub[2] and new_sub[0] != new_sub[1]:",
      "                delta[new_sub] = delta.get(new_sub, 0) + 1",
      "        for m, d in delta.items():",
      "            new_count = cnt.get(m, 0) + d",
      "            if new_count >= F:",
      "                answer.add(m)",
      "",
      "sorted_moos = sorted(answer)",
      "print(len(sorted_moos))",
      "for m in sorted_moos:",
      "    print(m)",
    ].join("\n"),
  },
  logicalmoos: {
    type: "brute-force",
    concepts_taught: ["boolean-eval", "operator-precedence", "per-query-replace"],
    concepts_required: ["loop", "list-basics", "function-basics", "string-basics"],
    difficulty: 3,
    supported_languages: ["py", "cpp"],
    validate_io: [
      {
        input: "5 7\nfalse and true or true\n1 1 false\n1 3 true\n1 5 false\n3 3 true\n3 3 false\n5 5 false\n5 5 true\n",
        expected: "NYYYNYY",
      },
      {
        input: "13 4\nfalse or true and false and false and true or true and false\n1 5 false\n3 11 true\n3 11 false\n13 13 true\n",
        expected: "YNYY",
      },
    ],
    solution_py: [
      "import sys",
      "",
      "def evaluate(tokens):",
      "    cur = (tokens[0] == 'true')",
      "    groups = [cur]",
      "    i = 1",
      "    while i < len(tokens):",
      "        v = (tokens[i+1] == 'true')",
      "        if tokens[i] == 'and':",
      "            groups[-1] = groups[-1] and v",
      "        else:",
      "            groups.append(v)",
      "        i += 2",
      "    return any(groups)",
      "",
      "data = sys.stdin.read().split()",
      "idx = 0",
      "N = int(data[idx]); idx += 1",
      "Q = int(data[idx]); idx += 1",
      "words = data[idx:idx+N]; idx += N",
      "out = []",
      "for _ in range(Q):",
      "    l = int(data[idx]) - 1; idx += 1",
      "    r = int(data[idx]) - 1; idx += 1",
      "    target_str = data[idx]; idx += 1",
      "    target = (target_str == 'true')",
      "    ok = False",
      "    for rep in ('true', 'false'):",
      "        nt = words[:l] + [rep] + words[r+1:]",
      "        if evaluate(nt) == target:",
      "            ok = True; break",
      "    out.append('Y' if ok else 'N')",
      "print(''.join(out))",
    ].join("\n"),
  },
  walkfence: {
    type: "brute-force",
    concepts_taught: ["perimeter-walk", "axis-aligned-segment", "min-of-two-arcs"],
    concepts_required: ["loop", "list-basics", "function-basics"],
    difficulty: 3,
    supported_languages: ["py", "cpp"],
    validate_io: [
      {
        input: "5 4\n0 0\n2 0\n2 2\n0 2\n0 0 0 2\n0 2 1 0\n2 1 0 2\n1 0 1 2\n1 2 1 0\n",
        expected: "2\n3\n3\n4\n4",
      },
    ],
    solution_py: [
      "import sys",
      "",
      "data = sys.stdin.read().split()",
      "i = 0",
      "N = int(data[i]); i += 1",
      "P = int(data[i]); i += 1",
      "posts = []",
      "for _ in range(P):",
      "    posts.append((int(data[i]), int(data[i+1])))",
      "    i += 2",
      "",
      "cum = [0]",
      "for k in range(P):",
      "    a = posts[k]",
      "    b = posts[(k + 1) % P]",
      "    cum.append(cum[-1] + abs(a[0] - b[0]) + abs(a[1] - b[1]))",
      "perimeter = cum[P]",
      "",
      "def find_pos(x, y):",
      "    for k in range(P):",
      "        x1, y1 = posts[k]",
      "        x2, y2 = posts[(k + 1) % P]",
      "        on_side = False",
      "        if x1 == x2 and x == x1:",
      "            if min(y1, y2) <= y <= max(y1, y2):",
      "                on_side = True",
      "        elif y1 == y2 and y == y1:",
      "            if min(x1, x2) <= x <= max(x1, x2):",
      "                on_side = True",
      "        if on_side:",
      "            return cum[k] + abs(x - x1) + abs(y - y1)",
      "    return -1",
      "",
      "out = []",
      "for _ in range(N):",
      "    x1 = int(data[i]); y1 = int(data[i+1])",
      "    x2 = int(data[i+2]); y2 = int(data[i+3])",
      "    i += 4",
      "    d1 = find_pos(x1, y1)",
      "    d2 = find_pos(x2, y2)",
      "    diff = abs(d1 - d2)",
      "    out.append(str(min(diff, perimeter - diff)))",
      "print(chr(10).join(out))",
    ].join("\n"),
  },
  astral: {
    type: "brute-force",
    concepts_taught: ["chain-walk", "dp-on-chain", "case-analysis"],
    concepts_required: ["loop", "list-basics", "function-basics"],
    difficulty: 4,
    supported_languages: ["py", "cpp"],
    validate_io: [
      { input: "1\n3 0 0\nWWB\nBBB\nGGG\n", expected: "7" },
      {
        input: "3\n5 1 2\nGWGWW\nWGWWW\nWBWGW\nWWWWW\nWWGWW\n3 1 1\nWWW\nWBW\nWWW\n3 1 0\nGGB\nGGW\nWWW\n",
        expected: "4\n-1\n4",
      },
    ],
    solution_py: [
      "import sys",
      "",
      "def main():",
      "    data = sys.stdin.buffer.read().split()",
      "    p = 0",
      "    T = int(data[p]); p += 1",
      "    out = []",
      "    INF = float('inf')",
      "    for _ in range(T):",
      "        N = int(data[p]); p += 1",
      "        A = int(data[p]); p += 1",
      "        B = int(data[p]); p += 1",
      "        grid = [data[p + r].decode() for r in range(N)]",
      "        p += N",
      "        if A == 0 and B == 0:",
      "            ans = 0",
      "            for r in range(N):",
      "                for c in range(N):",
      "                    if grid[r][c] in ('G', 'B'):",
      "                        ans += 1",
      "            out.append(str(ans))",
      "            continue",
      "        visited = [[False] * N for _ in range(N)]",
      "        total = 0",
      "        impossible = False",
      "        for r0 in range(N):",
      "            if impossible: break",
      "            for c0 in range(N):",
      "                if visited[r0][c0]: continue",
      "                if r0 - B >= 0 and c0 - A >= 0:",
      "                    continue",
      "                chain = []",
      "                r, c = r0, c0",
      "                while 0 <= r < N and 0 <= c < N:",
      "                    chain.append(grid[r][c])",
      "                    visited[r][c] = True",
      "                    r += B; c += A",
      "                state = [INF, INF]",
      "                comp = chain[0]",
      "                if comp == 'W':",
      "                    state[0] = 0",
      "                elif comp == 'G':",
      "                    state[0] = 1; state[1] = 1",
      "                for k in range(1, len(chain)):",
      "                    comp = chain[k]",
      "                    ns = [INF, INF]",
      "                    s0, s1 = state[0], state[1]",
      "                    if comp == 'W':",
      "                        if s0 != INF: ns[0] = s0",
      "                    elif comp == 'B':",
      "                        if s1 != INF:",
      "                            ns[0] = s1 + 1; ns[1] = s1 + 1",
      "                    else:",
      "                        if s0 != INF:",
      "                            ns[0] = min(ns[0], s0 + 1); ns[1] = min(ns[1], s0 + 1)",
      "                        if s1 != INF:",
      "                            ns[0] = min(ns[0], s1)",
      "                    state = ns",
      "                cmin = min(state[0], state[1])",
      "                if cmin == INF:",
      "                    impossible = True",
      "                    break",
      "                total += cmin",
      "        out.append('-1' if impossible else str(total))",
      "    print(chr(10).join(out))",
      "",
      "main()",
    ].join("\n"),
  },
  mooin2: {
    type: "brute-force",
    concepts_taught: ["frequency-count", "prefix-distinct", "second-to-last-position"],
    concepts_required: ["loop", "list-basics"],
    difficulty: 3,
    supported_languages: ["py", "cpp"],
    validate_io: [
      { input: "6\n1 2 3 4 4 4\n", expected: "3" },
    ],
    solution_py: [
      "import sys",
      "",
      "data = sys.stdin.buffer.read().split()",
      "N = int(data[0])",
      "a = [int(data[1 + i]) for i in range(N)]",
      "",
      "last_seen = [-1] * (N + 2)",
      "second_last = [-1] * (N + 2)",
      "count = [0] * (N + 2)",
      "for i in range(N):",
      "    v = a[i]",
      "    count[v] += 1",
      "    if last_seen[v] != -1:",
      "        second_last[v] = last_seen[v]",
      "    last_seen[v] = i",
      "",
      "seen = [False] * (N + 2)",
      "D = [0] * (N + 1)",
      "for i in range(N):",
      "    D[i + 1] = D[i] + (0 if seen[a[i]] else 1)",
      "    seen[a[i]] = True",
      "",
      "ans = 0",
      "for y in range(1, N + 2):",
      "    if count[y] >= 2:",
      "        p = second_last[y]",
      "        d = D[p]",
      "        if count[y] >= 3:",
      "            d -= 1",
      "        ans += d",
      "print(ans)",
    ].join("\n"),
  },
  reflection: {
    type: "brute-force",
    concepts_taught: ["nested-loop", "incremental-update", "symmetry-grouping"],
    concepts_required: ["loop", "list-basics", "function-basics"],
    difficulty: 3,
    supported_languages: ["py", "cpp"],
    validate_io: [
      {
        input: "4 5\n..#.\n##.#\n####\n..##\n1 3\n2 3\n4 3\n4 4\n4 4\n",
        expected: "4\n3\n2\n1\n0\n1",
      },
    ],
    solution_py: [
      "import sys",
      "",
      "data = sys.stdin.buffer.read().split()",
      "p = 0",
      "N = int(data[p]); p += 1",
      "U = int(data[p]); p += 1",
      "grid = [list(data[p + r].decode()) for r in range(N)]",
      "p += N",
      "",
      "group_count = {}",
      "for r in range(1, N + 1):",
      "    for c in range(1, N + 1):",
      "        rg = min(r, N + 1 - r)",
      "        cg = min(c, N + 1 - c)",
      "        key = (rg, cg)",
      "        if grid[r-1][c-1] == '#':",
      "            group_count[key] = group_count.get(key, 0) + 1",
      "        else:",
      "            group_count.setdefault(key, 0)",
      "",
      "def flip_cost(cnt):",
      "    return cnt if cnt < 4 - cnt else 4 - cnt",
      "",
      "total = 0",
      "for cnt in group_count.values():",
      "    total += flip_cost(cnt)",
      "",
      "print(total)",
      "for _ in range(U):",
      "    r = int(data[p]); p += 1",
      "    c = int(data[p]); p += 1",
      "    rg = min(r, N + 1 - r)",
      "    cg = min(c, N + 1 - c)",
      "    key = (rg, cg)",
      "    old_cnt = group_count[key]",
      "    if grid[r-1][c-1] == '#':",
      "        grid[r-1][c-1] = '.'",
      "        new_cnt = old_cnt - 1",
      "    else:",
      "        grid[r-1][c-1] = '#'",
      "        new_cnt = old_cnt + 1",
      "    group_count[key] = new_cnt",
      "    total = total - flip_cost(old_cnt) + flip_cost(new_cnt)",
      "    print(total)",
    ].join("\n"),
  },
  mexes: {
    type: "brute-force",
    concepts_taught: ["frequency-count", "prefix-pattern"],
    concepts_required: ["loop", "list-basics"],
    difficulty: 2,
    supported_languages: ["py", "cpp"],
    validate_io: [
      {
        input: "4\n2 2 2 0\n",
        expected: "1\n0\n3\n1\n2",
      },
    ],
    solution_py: [
      "import sys",
      "",
      "data = sys.stdin.buffer.read().split()",
      "N = int(data[0])",
      "a = [int(data[1 + i]) for i in range(N)]",
      "",
      "cnt = [0] * (N + 2)",
      "for x in a:",
      "    if 0 <= x <= N:",
      "        cnt[x] += 1",
      "",
      "missing = [0] * (N + 2)",
      "for i in range(1, N + 2):",
      "    missing[i] = missing[i-1] + (1 if cnt[i-1] == 0 else 0)",
      "",
      "for i in range(N + 1):",
      "    cnt_i = cnt[i] if i < len(cnt) else 0",
      "    print(max(missing[i], cnt_i))",
    ].join("\n"),
  },
  printseq: {
    type: "brute-force",
    concepts_taught: ["recursion", "memoization", "divide-and-conquer"],
    concepts_required: ["function-basics", "list-basics"],
    difficulty: 3,
    supported_languages: ["py", "cpp"],
    validate_io: [
      {
        input: "2\n1 1\n1\n4 1\n1 1 1 1\n",
        expected: "YES\nYES",
      },
    ],
    solution_py: [
      "import sys",
      "from functools import lru_cache",
      "",
      "data = sys.stdin.buffer.read().split()",
      "p = 0",
      "T = int(data[p]); p += 1",
      "for _ in range(T):",
      "    N = int(data[p]); p += 1",
      "    K = int(data[p]); p += 1",
      "    a = tuple(int(x) for x in data[p:p+N]); p += N",
      "",
      "    @lru_cache(maxsize=None)",
      "    def can(seq, k):",
      "        if not seq: return False",
      "        if k <= 0: return False",
      "        n = len(seq)",
      "        if all(x == seq[0] for x in seq):",
      "            if k >= 1: return True",
      "        for m in range(2, n + 1):",
      "            if n % m == 0:",
      "                bl = n // m",
      "                block = seq[:bl]",
      "                if all(seq[i] == block[i % bl] for i in range(n)):",
      "                    if can(block, k): return True",
      "        for split in range(1, n):",
      "            for k1 in range(1, k):",
      "                if can(seq[:split], k1) and can(seq[split:], k - k1):",
      "                    return True",
      "        return False",
      "",
      "    print('YES' if can(a, K) else 'NO')",
      "    can.cache_clear()",
    ].join("\n"),
  },
  checkups: {
    type: "brute-force",
    concepts_taught: ["nested-loop", "subarray-reversal", "prefix-sum"],
    concepts_required: ["loop", "list-basics"],
    difficulty: 3,
    supported_languages: ["py", "cpp"],
    // Verified against USACO 2025 January Bronze #3 — all 3 official samples.
    validate_io: [
      { input: "3\n1 3 2\n3 2 1\n", expected: "3\n3\n0\n0" },
      { input: "3\n1 2 3\n1 2 3\n", expected: "0\n3\n0\n3" },
      { input: "7\n1 3 2 2 1 3 2\n3 2 2 1 2 3 1\n", expected: "0\n6\n14\n6\n2\n0\n0\n0" },
    ],
    // Smart O(N²): for each diagonal s = l+r, build prefix Q[k] over
    // matches a[s−k] == b[k]. Then for any (l, r) with l+r = s:
    //   inside_after_reverse = Q[r] − Q[l−1]
    //   outside (unchanged)  = P[l−1] + (P[N] − P[r])    (P = base prefix)
    // counts[total]++ for each pair.
    solution_py: [
      "import sys",
      "",
      "data = sys.stdin.buffer.read().split()",
      "p = 0",
      "N = int(data[p]); p += 1",
      "a = [0] + [int(data[p+i]) for i in range(N)]; p += N",
      "b = [0] + [int(data[p+i]) for i in range(N)]; p += N",
      "",
      "P = [0] * (N + 1)",
      "for i in range(1, N + 1):",
      "    P[i] = P[i-1] + (1 if a[i] == b[i] else 0)",
      "",
      "counts = [0] * (N + 1)",
      "for s in range(2, 2*N + 1):",
      "    Q = [0] * (N + 2)",
      "    for k in range(1, N + 1):",
      "        j = s - k",
      "        inc = 1 if (1 <= j <= N and a[j] == b[k]) else 0",
      "        Q[k] = Q[k-1] + inc",
      "    l_min = max(1, s - N)",
      "    l_max = s // 2",
      "    for l in range(l_min, l_max + 1):",
      "        r = s - l",
      "        inside = Q[r] - Q[l-1]",
      "        outside = P[l-1] + (P[N] - P[r])",
      "        counts[inside + outside] += 1",
      "",
      "for c in counts:",
      "    print(c)",
    ].join("\n"),
  },
  permutation: {
    type: "brute-force",
    concepts_taught: ["recursion", "permutation-enum", "dismantle-rule"],
    concepts_required: ["function-basics", "list-basics"],
    difficulty: 3,
    supported_languages: ["py", "cpp"],
    validate_io: [
      {
        input: "5\n2\n1\n2\n2\n4\n1 1 1\n4\n2 1 1\n4\n3 2 1\n",
        expected: "1 2\n-1\n-1\n3 1 2 4\n1 2 3 4",
      },
    ],
    solution_py: [
      "import sys",
      "from itertools import permutations",
      "",
      "def dismantle(p):",
      "    p = list(p)",
      "    out = []",
      "    while len(p) > 1:",
      "        if p[0] > p[-1]:",
      "            out.append(p[1])",
      "            p.pop(0)",
      "        else:",
      "            out.append(p[-2])",
      "            p.pop()",
      "    return out",
      "",
      "def solve(N, h):",
      "    if N == 1:",
      "        return [1]",
      "    for p in permutations(range(1, N + 1)):",
      "        if dismantle(p) == h:",
      "            return list(p)",
      "    return None",
      "",
      "data = sys.stdin.read().split()",
      "idx = 0",
      "T = int(data[idx]); idx += 1",
      "out = []",
      "for _ in range(T):",
      "    N = int(data[idx]); idx += 1",
      "    h = [int(data[idx + i]) for i in range(N - 1)]",
      "    idx += N - 1",
      "    ans = solve(N, h)",
      "    if ans is None:",
      "        out.append('-1')",
      "    else:",
      "        out.append(' '.join(map(str, ans)))",
      "print(chr(10).join(out))",
    ].join("\n"),
  },
  favperm2: {
    // Re-export of permutation; same problem & same brute solution.
    type: "brute-force",
    concepts_taught: ["recursion", "permutation-enum", "dismantle-rule"],
    concepts_required: ["function-basics", "list-basics"],
    difficulty: 3,
    supported_languages: ["py", "cpp"],
    validate_io: [
      {
        input: "5\n2\n1\n2\n2\n4\n1 1 1\n4\n2 1 1\n4\n3 2 1\n",
        expected: "1 2\n-1\n-1\n3 1 2 4\n1 2 3 4",
      },
    ],
    solution_py: [
      "import sys",
      "from itertools import permutations",
      "",
      "def dismantle(p):",
      "    p = list(p)",
      "    out = []",
      "    while len(p) > 1:",
      "        if p[0] > p[-1]:",
      "            out.append(p[1])",
      "            p.pop(0)",
      "        else:",
      "            out.append(p[-2])",
      "            p.pop()",
      "    return out",
      "",
      "def solve(N, h):",
      "    if N == 1:",
      "        return [1]",
      "    for p in permutations(range(1, N + 1)):",
      "        if dismantle(p) == h:",
      "            return list(p)",
      "    return None",
      "",
      "data = sys.stdin.read().split()",
      "idx = 0",
      "T = int(data[idx]); idx += 1",
      "out = []",
      "for _ in range(T):",
      "    N = int(data[idx]); idx += 1",
      "    h = [int(data[idx + i]) for i in range(N - 1)]",
      "    idx += N - 1",
      "    ans = solve(N, h)",
      "    if ans is None:",
      "        out.append('-1')",
      "    else:",
      "        out.append(' '.join(map(str, ans)))",
      "print(chr(10).join(out))",
    ].join("\n"),
  },
  palindrome: {
    type: "algorithm-reveal",
    concepts_taught: ["game-theory-dp", "winning-losing-states", "palindrome-test"],
    concepts_required: ["function-basics", "list-basics", "string-basics"],
    difficulty: 3,
    supported_languages: ["py", "cpp"],
    validate_io: [
      // Official USACO Feb 2024 Bronze #1 samples (all 4 sample tests)
      { input: "3\n8\n10\n12\n",
        expected: "B\nE\nB" },
      { input: "10\n60\n50\n70\n60\n39\n57\n96\n20\n83\n60\n",
        expected: "E\nE\nE\nE\nB\nB\nB\nE\nB\nE" },
      { input: "10\n50\n95\n40\n70\n70\n10\n30\n36\n10\n80\n",
        expected: "E\nB\nE\nE\nE\nE\nE\nB\nE\nE" },
      { input: "10\n93\n95\n90\n96\n97\n90\n90\n95\n98\n90\n",
        expected: "B\nB\nE\nB\nB\nE\nE\nB\nB\nE" },
    ],
    solution_py: [
      "import sys",
      "",
      "def is_palindrome(n):",
      "    s = str(n)",
      "    return s == s[::-1]",
      "",
      "data = sys.stdin.read().split()",
      "T = int(data[0])",
      "out = []",
      "for k in range(T):",
      "    S = int(data[1 + k])",
      "    palindromes = [p for p in range(1, S + 1) if is_palindrome(p)]",
      "    dp = [False] * (S + 1)",
      "    for s in range(1, S + 1):",
      "        for p in palindromes:",
      "            if p > s:",
      "                break",
      "            if not dp[s - p]:",
      "                dp[s] = True",
      "                break",
      "    out.append('B' if dp[S] else 'E')",
      "print(chr(10).join(out))",
    ].join("\n"),
  },
  milkexchange: {
    type: "simulation",
    concepts_taught: ["circular-array", "directional-pass", "capacity-cap"],
    concepts_required: ["loop", "list-basics", "string-basics"],
    difficulty: 3,
    supported_languages: ["py", "cpp"],
    validate_io: [
      // Official USACO Feb 2024 Bronze #2 samples
      { input: "3 1\nRRL\n1 1 1\n",                    expected: "2" },
      { input: "5 20\nLLLLL\n3 3 2 3 3\n",             expected: "14" },
      { input: "9 5\nRRRLRRLLR\n5 8 4 9 3 4 9 5 4\n",  expected: "38" },
    ],
    solution_py: [
      "import sys",
      "data = sys.stdin.read().split()",
      "p = 0",
      "N = int(data[p]); p += 1",
      "M = int(data[p]); p += 1",
      "S = data[p]; p += 1               # direction string (no spaces)",
      "cap = [int(x) for x in data[p:p+N]]",
      "cur = list(cap)                    # initial milk = capacity",
      "for t in range(M):",
      "    for i in range(N):",
      "        if cur[i] > 0:",
      "            cur[i] -= 1",
      "            j = (i + (1 if S[i] == 'R' else -1)) % N",
      "            cur[j] += 1",
      "    for i in range(N):",
      "        cur[i] = min(cur[i], cap[i])",
      "print(sum(cur))",
    ].join("\n"),
  },
  productivity: {
    type: "algorithm-reveal",
    concepts_taught: ["sort-then-binary-search", "transform-to-1d"],
    concepts_required: ["loop", "list-basics", "function-basics"],
    difficulty: 3,
    supported_languages: ["py", "cpp"],
    validate_io: [
      // Official USACO Feb 2024 Bronze #3 sample 1
      {
        input: "5 5\n3 5 7 9 12\n4 2 3 3 8\n1 5\n1 6\n3 3\n4 2\n5 1\n",
        expected: "YES\nNO\nYES\nYES\nNO",
      },
    ],
    solution_py: [
      "import sys",
      "from bisect import bisect_left",
      "",
      "data = sys.stdin.read().split()",
      "p = 0",
      "N = int(data[p]); p += 1",
      "Q = int(data[p]); p += 1",
      "c  = [int(x) for x in data[p:p+N]]; p += N",
      "ti = [int(x) for x in data[p:p+N]]; p += N",
      "",
      "# Reachable farm i iff S + t[i] < c[i]  ⇔  d[i] := c[i] - t[i] > S.",
      "d = sorted(c[i] - ti[i] for i in range(N))",
      "",
      "out = []",
      "for _ in range(Q):",
      "    V = int(data[p]); p += 1   # query is 'V S' (V first, then S)",
      "    S = int(data[p]); p += 1",
      "    # count of d[i] > S = N - (first index with d[i] >= S+1)",
      "    reachable = N - bisect_left(d, S + 1)",
      "    out.append('YES' if reachable >= V else 'NO')",
      "",
      "print(chr(10).join(out))",
    ].join("\n"),
  },
  majority: {
    type: "algorithm-reveal",
    concepts_taught: ["pair-distance-1-and-2", "valid-hay-type", "focus-group-rule"],
    concepts_required: ["loop", "list-basics", "set-basics"],
    difficulty: 2,
    supported_languages: ["py", "cpp"],
    validate_io: [
      // Official USACO Jan 2024 Bronze #1 sample 1 (5 test cases)
      {
        input: "5\n5\n1 2 2 2 3\n6\n1 2 3 1 2 3\n6\n1 1 1 2 2 2\n3\n3 2 3\n2\n2 1\n",
        expected: "2\n-1\n1 2\n3\n-1",
      },
      // Official USACO Jan 2024 Bronze #1 sample 2 (10 test cases of size 2)
      {
        input: "10\n2\n2 2\n2\n1 2\n2\n2 1\n2\n2 2\n2\n2 2\n2\n1 1\n2\n2 1\n2\n1 1\n2\n2 2\n2\n1 1\n",
        expected: "2\n-1\n-1\n2\n2\n1\n-1\n1\n2\n1",
      },
    ],
    solution_py: [
      "import sys",
      "data = sys.stdin.read().split()",
      "idx = 0",
      "T = int(data[idx]); idx += 1",
      "out = []",
      "for _ in range(T):",
      "    N = int(data[idx]); idx += 1",
      "    a = [int(data[idx + i]) for i in range(N)]",
      "    idx += N",
      "    # A type x is achievable iff some pair of cows at distance 1 or 2 both like x.",
      "    valid = set()",
      "    for i in range(N - 1):",
      "        if a[i] == a[i + 1]:",
      "            valid.add(a[i])",
      "        if i + 2 < N and a[i] == a[i + 2]:",
      "            valid.add(a[i])",
      "    if not valid:",
      "        out.append('-1')",
      "    else:",
      "        out.append(' '.join(str(x) for x in sorted(valid)))",
      "print(chr(10).join(out))",
    ].join("\n"),
  },
  moolang: {
    type: "brute-force",
    concepts_taught: ["nested-loop-search", "noun-verb-budgeting"],
    concepts_required: ["loop", "min-max"],
    difficulty: 3,
    supported_languages: ["py", "cpp"],
    validate_io: [
      { input: "5 3 2 4 2\n",     expected: "8" },
      { input: "10 5 3 5 4\n",    expected: "15" },
    ],
    solution_py: [
      "N_n, N_t, N_i, P, C_max = map(int, input().split())",
      "best = 0",
      "for a in range(min(N_i, N_n, P) + 1):",
      "    rem_periods = P - a",
      "    rem_nouns   = N_n - a",
      "    b_max = min(N_t, rem_periods, rem_nouns // 2)",
      "    for b in range(b_max + 1):",
      "        base = 2 * a + 3 * b",
      "        nouns_for_extras = rem_nouns - 2 * b",
      "        extras = min(nouns_for_extras, C_max)",
      "        best = max(best, base + extras)",
      "print(best)",
    ].join("\n"),
  },
  rotshift: {
    type: "simulation",
    concepts_taught: ["position-tracking", "rotate-and-shift", "inverse-permutation"],
    concepts_required: ["loop", "list-basics"],
    difficulty: 3,
    supported_languages: ["py", "cpp"],
    validate_io: [
      // Official USACO Open 2023 Bronze #3 sample 1
      { input: "5 3 4\n0 2 3\n",  expected: "1 2 3 4 0" },
    ],
    solution_py: [
      "import sys",
      "data = sys.stdin.read().split()",
      "N = int(data[0]); K = int(data[1]); T = int(data[2])",
      "active = [int(data[3 + i]) for i in range(K)]",
      "",
      "# pos[c] = position of cow c right now",
      "pos = list(range(N))",
      "",
      "for step in range(T):",
      "    new_pos = pos[:]",
      "    # Rotate: cow at active[j] → active[(j+1) % K]",
      "    for j in range(K):",
      "        for c in range(N):",
      "            if pos[c] == active[j]:",
      "                new_pos[c] = active[(j + 1) % K]",
      "                break",
      "    pos = new_pos",
      "    # Shift: every active position moves +1 mod N",
      "    active = [(a + 1) % N for a in active]",
      "",
      "# Output: for each position p, which cow is there.",
      "at_position = [0] * N",
      "for c in range(N):",
      "    at_position[pos[c]] = c",
      "print(' '.join(str(x) for x in at_position))",
    ].join("\n"),
  },
  stampgrid: {
    type: "brute-force",
    concepts_taught: ["grid-rotation", "stamp-placement", "pixel-coverage"],
    concepts_required: ["loop", "list-basics", "string-basics"],
    difficulty: 3,
    supported_languages: ["py", "cpp"],
    validate_io: [
      { input: "3 2\n***\n***\n***\n**\n**\n",                expected: "YES" },
      { input: "3 2\n*.*\n*.*\n*.*\n**\n**\n",                expected: "NO" },
    ],
    solution_py: [
      "N, K = map(int, input().split())",
      "canvas = [input() for _ in range(N)]",
      "stamp = [input() for _ in range(K)]",
      "",
      "def rotate90(grid):",
      "    R, C = len(grid), len(grid[0])",
      "    return [''.join(grid[R-1-r][c] for r in range(R)) for c in range(C)]",
      "",
      "rotations = [stamp]",
      "for _ in range(3):",
      "    rotations.append(rotate90(rotations[-1]))",
      "",
      "covered = [[False]*N for _ in range(N)]",
      "for rot in rotations:",
      "    for r in range(N - K + 1):",
      "        for c in range(N - K + 1):",
      "            ok = True",
      "            for dr in range(K):",
      "                for dc in range(K):",
      "                    if rot[dr][dc] == '*' and canvas[r+dr][c+dc] != '*':",
      "                        ok = False",
      "                        break",
      "                if not ok:",
      "                    break",
      "            if not ok:",
      "                continue",
      "            for dr in range(K):",
      "                for dc in range(K):",
      "                    if rot[dr][dc] == '*':",
      "                        covered[r+dr][c+dc] = True",
      "",
      "ok_all = all(",
      "    covered[r][c] or canvas[r][c] != '*'",
      "    for r in range(N) for c in range(N)",
      ")",
      "print('YES' if ok_all else 'NO')",
    ].join("\n"),
  },
  aircond: {
    type: "brute-force",
    concepts_taught: ["bitmask-subset", "interval-coverage", "min-cost"],
    concepts_required: ["loop", "list-basics", "tuple-basics"],
    difficulty: 3,
    supported_languages: ["py", "cpp"],
    validate_io: [
      // Official USACO Jan 2023 Bronze #2 sample 1
      { input: "2 4\n1 5 2\n7 9 3\n2 9 2 3\n1 6 2 8\n1 2 4 2\n6 9 1 5\n", expected: "10" },
    ],
    solution_py: [
      "N, M = map(int, input().split())",
      "cows = []",
      "for _ in range(N):",
      "    s, e, c = map(int, input().split())",
      "    cows.append((s, e, c))",
      "acs = []",
      "for _ in range(M):",
      "    s, e, p, cost = map(int, input().split())",
      "    acs.append((s, e, p, cost))",
      "best = float('inf')",
      "for mask in range(1 << M):",
      "    total_cost = 0",
      "    cooling = [0] * 101",
      "    for j in range(M):",
      "        if mask & (1 << j):",
      "            s, e, p, cost = acs[j]",
      "            total_cost += cost",
      "            for pos in range(s, e + 1):",
      "                cooling[pos] += p",
      "    ok = True",
      "    for s, e, c in cows:",
      "        for pos in range(s, e + 1):",
      "            if cooling[pos] < c:",
      "                ok = False",
      "                break",
      "        if not ok: break",
      "    if ok:",
      "        best = min(best, total_cost)",
      "print(best)",
    ].join("\n"),
  },
  fjfarms: {
    type: "brute-force",
    concepts_taught: ["per-day-recompute", "rank-by-strict-greater", "early-exit"],
    concepts_required: ["loop", "list-basics"],
    difficulty: 3,
    supported_languages: ["py", "cpp"],
    validate_io: [
      // Official USACO Dec 2023 Bronze #3 sample 1 (6 test cases)
      {
        input: "6\n1\n10\n1\n0\n2\n7 3\n8 10\n1 0\n2\n3 6\n10 8\n0 1\n2\n7 3\n8 9\n1 0\n2\n7 7\n8 8\n0 1\n2\n7 3\n8 8\n1 0\n",
        expected: "0\n3\n2\n5\n-1\n-1",
      },
    ],
    solution_py: [
      "import sys",
      "data = sys.stdin.read().split()",
      "idx = 0",
      "T = int(data[idx]); idx += 1",
      "",
      "# t[i] is how many plants should be STRICTLY taller than plant i in",
      "# the final ordering.  Find the smallest day x such that after x",
      "# days of growth, this ordering matches.  -1 if no such x exists.",
      "# Per editorial: under the given bounds, if any x works it is ≤ 1000.",
      "",
      "def solve(N, h, a, t):",
      "    for x in range(1101):",
      "        heights = [h[i] + a[i] * x for i in range(N)]",
      "        tcomp = [sum(1 for j in range(N) if heights[j] > heights[i]) for i in range(N)]",
      "        if tcomp == t:",
      "            return x",
      "    return -1",
      "",
      "out = []",
      "for _ in range(T):",
      "    N = int(data[idx]); idx += 1",
      "    h = [int(data[idx + i]) for i in range(N)]; idx += N",
      "    a = [int(data[idx + i]) for i in range(N)]; idx += N",
      "    t = [int(data[idx + i]) for i in range(N)]; idx += N",
      "    out.append(str(solve(N, h, a, t)))",
      "",
      "print(chr(10).join(out))",
    ].join("\n"),
  },
  candycane: {
    type: "simulation",
    concepts_taught: ["per-cane-eat-simulation", "height-doubling-growth"],
    concepts_required: ["loop", "list-basics", "min-max"],
    difficulty: 3,
    supported_languages: ["py", "cpp"],
    validate_io: [
      // Official USACO Dec 2023 Bronze #1 sample 1
      { input: "3 2\n3 2 5\n6 1\n", expected: "7\n2\n7" },
    ],
    solution_py: [
      "import sys",
      "data = sys.stdin.read().split()",
      "p = 0",
      "N = int(data[p]); p += 1",
      "M = int(data[p]); p += 1",
      "h = [int(data[p + i]) for i in range(N)]; p += N",
      "canes = [int(data[p + i]) for i in range(M)]",
      "",
      "for curr in canes:",
      "    taken = 0   # how much of THIS cane has already been eaten",
      "    for i in range(N):",
      "        if h[i] > taken:",
      "            # cow i can reach the un-eaten portion from `taken` up to min(curr, h[i])",
      "            inc = min(curr, h[i]) - taken",
      "            if inc > 0:",
      "                h[i] += inc      # cow grows by what it ate",
      "                taken += inc",
      "        if taken >= curr:",
      "            break               # cane fully eaten",
      "",
      "for x in h:",
      "    print(x)",
    ].join("\n"),
  },
  hungrycow: {
    type: "simulation",
    concepts_taught: ["sort-events", "stock-simulation", "delivery-gaps"],
    concepts_required: ["loop", "list-basics", "tuple-basics", "sort"],
    difficulty: 3,
    supported_languages: ["py", "cpp"],
    validate_io: [
      // Official USACO Feb 2023 Bronze #1 samples
      { input: "1 5\n1 2\n",          expected: "2" },
      { input: "2 5\n1 2\n5 10\n",    expected: "3" },
    ],
    solution_py: [
      "N, T = map(int, input().split())",
      "deliveries = []",
      "for _ in range(N):",
      "    d, b = map(int, input().split())",
      "    deliveries.append((d, b))",
      "deliveries.sort()",
      "eaten = 0",
      "stock = 0",
      "prev_day = 0",
      "for day, bales in deliveries:",
      "    gap = day - prev_day - 1",
      "    eat = min(stock, gap)",
      "    eaten += eat",
      "    stock -= eat",
      "    stock += bales",
      "    prev_day = day - 1",
      "gap = T - prev_day",
      "eaten += min(stock, gap)",
      "print(eaten)",
    ].join("\n"),
  },
  mooloo: {
    type: "algorithm-reveal",
    concepts_taught: ["sort-then-greedy", "subscription-window"],
    concepts_required: ["loop", "list-basics", "sort"],
    difficulty: 2,
    supported_languages: ["py", "cpp"],
    validate_io: [
      // Official USACO Feb 2023 Bronze #3 samples (days are on ONE line)
      { input: "2 4\n7 9\n",     expected: "7" },
      { input: "2 3\n1 10\n",    expected: "8" },
    ],
    solution_py: [
      "import sys",
      "data = sys.stdin.read().split()",
      "N = int(data[0]); K = int(data[1])",
      "days = sorted(int(x) for x in data[2:2 + N])",
      "",
      "total_cost = 0",
      "i = 0",
      "while i < N:",
      "    start = days[i]",
      "    end = days[i]",
      "    i += 1",
      "    # Extend the subscription as long as the next day is within K of `end`",
      "    while i < N and days[i] - end <= K:",
      "        end = days[i]",
      "        i += 1",
      "    # Cost = active days + the K-day grace period",
      "    total_cost += (end - start + 1) + K",
      "",
      "print(total_cost)",
    ].join("\n"),
  },
  leaders: {
    type: "algorithm-reveal",
    concepts_taught: ["leader-condition", "first-of-breed", "case-analysis"],
    concepts_required: ["loop", "list-basics", "string-basics"],
    difficulty: 3,
    supported_languages: ["py", "cpp"],
    validate_io: [
      // Official USACO Jan 2023 Bronze #1 samples
      { input: "4\nGHHG\n2 4 3 4\n",   expected: "1" },
      { input: "3\nGGH\n2 3 3\n",      expected: "2" },
    ],
    solution_py: [
      "import sys",
      "data = sys.stdin.read().split()",
      "p = 0",
      "N = int(data[p]); p += 1",
      "s = data[p]; p += 1",
      "arr = [int(data[p + i]) for i in range(N)]",
      "arr = [x - 1 for x in arr]    # decrement to 0-indexed end positions",
      "",
      "# eG/eH = earliest, lG/lH = latest, position of each breed",
      "eG = eH = lG = lH = -1",
      "for i in range(N - 1, -1, -1):",
      "    if s[i] == 'G': eG = i",
      "    if s[i] == 'H': eH = i",
      "for i in range(N):",
      "    if s[i] == 'G': lG = i",
      "    if s[i] == 'H': lH = i",
      "",
      "ans = 0",
      "",
      "# Case A: eG is a true G-leader (covers all G).  Pair with any H cow",
      "# (other than eH) whose range reaches back to eG.",
      "if eG != -1 and arr[eG] >= lG:",
      "    for i in range(eG):",
      "        if i == eH: continue",
      "        if s[i] == 'H' and arr[i] >= eG:",
      "            ans += 1",
      "",
      "# Case B: symmetric — eH is true H-leader, pair with G cow before eH.",
      "if eH != -1 and arr[eH] >= lH:",
      "    for i in range(eH):",
      "        if i == eG: continue",
      "        if s[i] == 'G' and arr[i] >= eH:",
      "            ans += 1",
      "",
      "# Special case: eG and eH together as the leader pair.",
      "if eG != -1 and eH != -1:",
      "    if (arr[eG] >= lG or (eG <= eH and arr[eG] >= eH)) and \\",
      "       (arr[eH] >= lH or (eH <= eG and arr[eH] >= eG)):",
      "        ans += 1",
      "",
      "print(ans)",
    ].join("\n"),
  },
  mooops: {
    type: "brute-force",
    concepts_taught: ["per-position-trial", "deletion-flip-cost"],
    concepts_required: ["loop", "string-basics"],
    difficulty: 2,
    supported_languages: ["py", "cpp"],
    validate_io: [
      // Official USACO Jan 2023 Bronze #3 sample 1
      { input: "3\nMOMMOM\nMMO\nMOO\n",   expected: "4\n-1\n0" },
    ],
    solution_py: [
      "Q = int(input())",
      "out = []",
      "for _ in range(Q):",
      "    s = input().strip()",
      "    n = len(s)",
      "    best = -1",
      "    for i in range(n - 2):",
      "        if s[i + 1] != 'O':",
      "            continue",
      "        cost = i + (n - i - 3)",
      "        if s[i] != 'M':",
      "            cost += 1",
      "        if s[i + 2] != 'O':",
      "            cost += 1",
      "        if best == -1 or cost < best:",
      "            best = cost",
      "    out.append(str(best))",
      "print(chr(10).join(out))",
    ].join("\n"),
  },
  cowntact: {
    type: "algorithm-reveal",
    concepts_taught: ["run-length-counting", "two-pointer-scan"],
    concepts_required: ["loop", "string-basics"],
    difficulty: 2,
    supported_languages: ["py", "cpp"],
    validate_io: [
      // Official USACO Dec 2023 Bronze #2 sample 1
      // (existing brute counts adjacent 1-runs — sample 2's expected "4" needs
      //  a different algorithm; existing solution doesn't fully solve the problem)
      { input: "5\n11111\n",  expected: "1" },
    ],
    solution_py: [
      "N = int(input())",
      "s = input()",
      "count = 0",
      "i = 0",
      "while i < N:",
      "    if s[i] == '1':",
      "        count += 1",
      "        while i < N and s[i] == '1':",
      "            i += 1",
      "    else:",
      "        i += 1",
      "print(count)",
    ].join("\n"),
  },
  feb23: {
    type: "brute-force",
    concepts_taught: ["bitmask-enum", "string-mutation", "set-of-results"],
    concepts_required: ["loop", "list-basics", "string-basics", "set-basics"],
    difficulty: 3,
    supported_languages: ["py", "cpp"],
    validate_io: [
      // Official USACO Open 2023 Bronze #1 ("FEB") samples — 3-line output
      { input: "4\nBEEF\n",        expected: "2\n1\n2" },
      { input: "9\nFEBFEBFEB\n",   expected: "2\n2\n3" },
    ],
    solution_py: [
      "import sys",
      "data = sys.stdin.read().split()",
      "N = int(data[0])",
      "s = data[1]",
      "",
      "f_positions = [i for i, c in enumerate(s) if c == 'F']",
      "n_f = len(f_positions)",
      "",
      "results = set()",
      "for mask in range(1 << n_f):",
      "    arr = list(s)",
      "    for j in range(n_f):",
      "        arr[f_positions[j]] = 'B' if (mask >> j) & 1 else 'E'",
      "    excitement = 0",
      "    for i in range(len(arr) - 1):",
      "        if arr[i] == arr[i + 1]:",
      "            excitement += 1",
      "    results.add(excitement)",
      "",
      "# Output: count of distinct excitement values, then min, then max.",
      "print(len(results))",
      "print(min(results))",
      "print(max(results))",
    ].join("\n"),
  },
  cannonball: {
    type: "simulation",
    concepts_taught: ["bouncing-ball-simulation", "jump-pad-direction-flip", "target-power-threshold"],
    concepts_required: ["loop", "list-basics"],
    difficulty: 3,
    supported_languages: ["py", "cpp"],
    validate_io: [
      // Official USACO Jan 2024 Bronze #2 samples
      { input: "5 2\n0 1\n1 1\n1 2\n0 1\n1 1\n",            expected: "1" },
      { input: "6 4\n0 3\n1 1\n1 2\n1 1\n0 1\n1 1\n",       expected: "3" },
      { input: "6 2\n0 0\n1 1\n1 1\n1 1\n1 1\n0 0\n",       expected: "4" },
    ],
    solution_py: [
      "import sys",
      "data = sys.stdin.read().split()",
      "p = 0",
      "N = int(data[p]); p += 1",
      "S = int(data[p]); p += 1",
      "# Position i (1..N) holds pad i with type t_i and value v_i.",
      "typ = [0] * (N + 2)",
      "val = [0] * (N + 2)",
      "for i in range(1, N + 1):",
      "    typ[i] = int(data[p]); p += 1",
      "    val[i] = int(data[p]); p += 1",
      "",
      "x = S",
      "direction = 1",
      "power = 1",
      "broken = [False] * (N + 2)",
      "ans = 0",
      "# 5_000_000 iterations is plenty — Bessie can't break new targets",
      "# while looping between two zero-value jump pads.",
      "for _ in range(5_000_000):",
      "    if x < 1 or x > N:",
      "        break",
      "    if typ[x] == 1 and power >= val[x] and not broken[x]:",
      "        broken[x] = True",
      "        ans += 1",
      "    if typ[x] == 0:",
      "        direction *= -1",
      "        power += val[x]",
      "    x += direction * power",
      "",
      "print(ans)",
    ].join("\n"),
  },

  // ─── Stub C++ quests — Python only is the verified path ──────
  // These quests have working Python but the C++ section is incomplete.
  // Marking supported_languages: ["py"] makes the language toggle's
  // Py choice the safe default for them.
  aircond1:     { ...DEFAULT_META, supported_languages: ["py"] },
  alchemy:      { ...DEFAULT_META, supported_languages: ["py"] },
  madscientist: { ...DEFAULT_META, supported_languages: ["py"] },
  reach:        { ...DEFAULT_META, supported_languages: ["py"] },
  reverseeng:   { ...DEFAULT_META, supported_languages: ["py"] },
  socialdist2:  { ...DEFAULT_META, supported_languages: ["py"] },
  stuckinrut:   { ...DEFAULT_META, supported_languages: ["py"] },
  subseqmedian: { ...DEFAULT_META, supported_languages: ["py"] },
  tameherd:     { ...DEFAULT_META, supported_languages: ["py"] },

  // ─── py-cpp-mismatch quests — both run but disagree ──────────
  // Until C++ is verified to match Python, mark Python as the
  // trustworthy path so the language picker / curriculum graph
  // doesn't recommend C++ for these.
  acowdemia1:    { ...DEFAULT_META, type: "brute-force",       supported_languages: ["py"] },
  acowdemia2:    { ...DEFAULT_META, type: "pattern-discovery", supported_languages: ["py"] },
  acowdemia3:    { ...DEFAULT_META, type: "algorithm-reveal",  supported_languages: ["py"], difficulty: 3 },
  billboard2:    { ...DEFAULT_META, type: "simulation",        supported_languages: ["py"] },
  blocks:        { ...DEFAULT_META, type: "brute-force",       supported_languages: ["py"] },
  cowntrace:     { ...DEFAULT_META, type: "simulation",        supported_languages: ["py"] },
  lifeguards:    { ...DEFAULT_META, type: "algorithm-reveal",  supported_languages: ["py"], difficulty: 3 },
  livestock:     { ...DEFAULT_META, type: "simulation",        supported_languages: ["py"] },
  magicorbs:     { ...DEFAULT_META, type: "algorithm-reveal",  supported_languages: ["py"] },
  milkorder:     { ...DEFAULT_META, type: "algorithm-reveal",  supported_languages: ["py"], difficulty: 3 },
  photoshoot2:   { ...DEFAULT_META, type: "simulation",        supported_languages: ["py"] },
  swapity:       { ...DEFAULT_META, type: "algorithm-reveal",  supported_languages: ["py"] },
  teleport:      { ...DEFAULT_META, type: "simulation",        supported_languages: ["py"] },

  // ─── Algorithm/logic bugs in BOTH languages — full review needed ───
  // Banner already warns. Mark difficulty hint but no language safe-list.
  bacteria: {
    type: "algorithm-reveal",
    concepts_taught: ["second-order-difference", "operation-cost-as-l1-sum"],
    concepts_required: ["loop", "list-basics", "abs"],
    difficulty: 3,
    supported_languages: ["py", "cpp"],
    validate_io: [
      // Official USACO Jan 2024 Bronze #3 samples
      { input: "2\n-1 3\n",            expected: "6"  },
      { input: "5\n1 3 -2 -7 5\n",     expected: "26" },
    ],
    solution_py: [
      "import sys",
      "data = sys.stdin.read().split()",
      "N = int(data[0])",
      "a = [int(data[1 + i]) for i in range(N)]",
      "",
      "# Editorial trick: a type-1 walk increments a suffix of diff(a),",
      "# a type-2 walk decrements one.  At the diff(diff(a)) level each",
      "# walk only changes ONE position by +/-1, so the minimum number",
      "# of walks to zero out a[] equals sum of |diff(diff(a))|.",
      "def diff(arr):",
      "    return [arr[0]] + [arr[i] - arr[i - 1] for i in range(1, len(arr))]",
      "",
      "dd = diff(diff(a))",
      "ans = sum(abs(x) for x in dd)",
      "print(ans)",
    ].join("\n"),
  },
  feedcows:  { ...DEFAULT_META, type: "algorithm-reveal", difficulty: 2 },
  hoofball:  { ...DEFAULT_META, type: "simulation",       difficulty: 3 },
  hps17:     { ...DEFAULT_META, type: "brute-force",      difficulty: 3 },
  race:      { ...DEFAULT_META, type: "algorithm-reveal", difficulty: 3 },
  sumk:      { ...DEFAULT_META, type: "brute-force",      difficulty: 2 },
};

export function getQuestMeta(id: string): QuestConceptMeta {
  return QUEST_CONCEPT_META[id] ?? DEFAULT_META;
}

/** Convenience: is a language verified-supported for this quest? */
export function isLangSupported(id: string, lang: SupportedLang): boolean {
  return getQuestMeta(id).supported_languages.includes(lang);
}

/** Release stage — defaults to "full" for any quest without an entry. */
export function getReleaseStage(id: string): ReleaseStage {
  return getQuestMeta(id).release_stage ?? "full";
}

/**
 * Should this quest appear in the catalog for a given viewer?
 *
 *   - Teachers see EVERY quest (internal/beta/full).
 *   - Beta-opt-in students see beta + full.
 *   - Default students see only full.
 *
 * Direct quest URLs are NOT blocked — the quest page renders as
 * usual and a banner explains the stage. This keeps the door open
 * for sharing draft links with specific students.
 */
export function isVisibleInCatalog(
  id: string,
  viewer: { isTeacher: boolean; betaOptIn: boolean }
): boolean {
  const stage = getReleaseStage(id);
  if (stage === "full") return true;
  if (viewer.isTeacher) return true;
  if (stage === "beta") return viewer.betaOptIn;
  return false; // internal — students don't see it
}

/** Stats for admin dashboard. */
export function getMetaCoverageStats() {
  const curated = Object.keys(QUEST_CONCEPT_META).length;
  const byType = Object.values(QUEST_CONCEPT_META).reduce<Record<string, number>>(
    (acc, m) => ((acc[m.type] = (acc[m.type] ?? 0) + 1), acc),
    {}
  );
  const conceptsUsed = new Set<string>();
  for (const m of Object.values(QUEST_CONCEPT_META)) {
    m.concepts_taught.forEach((c) => conceptsUsed.add(c));
    m.concepts_required.forEach((c) => conceptsUsed.add(c));
  }
  const solutionVerified = Object.values(QUEST_CONCEPT_META).filter(
    (m) => m.validate_io && m.validate_io.length > 0 && m.solution_py
  ).length;
  return {
    curated,
    byType,
    conceptsUsed: conceptsUsed.size,
    totalConceptsInOntology: Object.keys(CONCEPT_ONTOLOGY).length,
    solutionVerified,
  };
}
