// Shared problem metadata — used by both server (generateStaticParams) and client UI

export interface ProblemMeta {
  id: string
  emoji: string
  title: string
  sub: string
  section: string
}

export const ALL_PROBLEMS: ProblemMeta[] = [
  // USACO
  {id:"rounding",emoji:"🔄",title:"Roundabout Rounding",sub:"Dec 2024 Bronze #1",section:"USACO"},
  {id:"cheese",emoji:"🧀",title:"Cheese Block",sub:"Dec 2024 Bronze #2",section:"USACO"},
  {id:"moo",emoji:"🐄",title:"It's Mooin' Time",sub:"Dec 2024 Bronze #3",section:"USACO"},
  {id:"permutation",emoji:"🔢",title:"FJ's Fav Permutation",sub:"Jan 2025 Bronze #1",section:"USACO"},
  {id:"interview",emoji:"🐄",title:"Bessie's Interview",sub:"Jan 2025 Bronze #2",section:"USACO"},
  {id:"balanced",emoji:"🔗",title:"Balanced Subsequences",sub:"Jan 2025 Bronze #3",section:"USACO"},
  {id:"checkups",emoji:"🐮",title:"Cow Checkups",sub:"Feb 2025 Bronze #1",section:"USACO"},
  {id:"exchange",emoji:"🥛",title:"Milk Exchange",sub:"Feb 2025 Bronze #2",section:"USACO"},
  {id:"presents",emoji:"🎁",title:"Stack of Presents",sub:"Feb 2025 Bronze #3",section:"USACO"},
  {id:"hps",emoji:"✊",title:"HPS Minus One",sub:"Open 2025 Bronze #1",section:"USACO"},
  {id:"cowphotos",emoji:"📸",title:"More Cow Photos",sub:"Open 2025 Bronze #2",section:"USACO"},
  {id:"mooin3",emoji:"🐄",title:"Mooin' Time III",sub:"Open 2025 Bronze #3",section:"USACO"},
  {id:"logicalmoos",emoji:"🧠",title:"Logical Moos",sub:"Open 2024 Bronze #1",section:"USACO"},
  {id:"walkfence",emoji:"🚶",title:"Walking Along a Fence",sub:"Open 2024 Bronze #2",section:"USACO"},
  {id:"favperm2",emoji:"🧩",title:"FJ's Fav Perm II",sub:"Open 2024 Bronze #3",section:"USACO"},
  {id:"palindrome",emoji:"🎲",title:"Palindrome Game",sub:"Feb 2024 Bronze #1",section:"USACO"},
  {id:"milkexchange",emoji:"🥛",title:"Milk Exchange",sub:"Feb 2024 Bronze #2",section:"USACO"},
  {id:"productivity",emoji:"📊",title:"Max Productivity",sub:"Feb 2024 Bronze #3",section:"USACO"},
  {id:"majority",emoji:"🗳️",title:"Majority Opinion",sub:"Jan 2024 Bronze #1",section:"USACO"},
  {id:"cannonball",emoji:"💥",title:"Cannonball",sub:"Jan 2024 Bronze #2",section:"USACO"},
  {id:"bacteria",emoji:"🦠",title:"Balancing Bacteria",sub:"Jan 2024 Bronze #3",section:"USACO"},
  {id:"candycane",emoji:"🍬",title:"Candy Cane Feast",sub:"Dec 2023 Bronze #1",section:"USACO"},
  {id:"cowntact",emoji:"🦠",title:"Cowntact Tracing 2",sub:"Dec 2023 Bronze #2",section:"USACO"},
  {id:"fjfarms",emoji:"🌱",title:"FJ Actually Farms",sub:"Dec 2023 Bronze #3",section:"USACO"},
  {id:"feb23",emoji:"🔤",title:"FEB",sub:"Open 2023 Bronze #1",section:"USACO"},
  {id:"moolang",emoji:"📝",title:"Moo Language",sub:"Open 2023 Bronze #2",section:"USACO"},
  {id:"rotshift",emoji:"🔄",title:"Rotate and Shift",sub:"Open 2023 Bronze #3",section:"USACO"},
  {id:"hungrycow",emoji:"🐄",title:"Hungry Cow",sub:"Feb 2023 Bronze #1",section:"USACO"},
  {id:"stampgrid",emoji:"📮",title:"Stamp Grid",sub:"Feb 2023 Bronze #2",section:"USACO"},
  {id:"mooloo",emoji:"📺",title:"Watching Mooloo",sub:"Feb 2023 Bronze #3",section:"USACO"},
  {id:"leaders",emoji:"👑",title:"Leaders",sub:"Jan 2023 Bronze #1",section:"USACO"},
  {id:"aircond",emoji:"❄️",title:"Air Cownditioning II",sub:"Jan 2023 Bronze #2",section:"USACO"},
  {id:"mooops",emoji:"🐮",title:"Moo Operations",sub:"Jan 2023 Bronze #3",section:"USACO"},
  {id:"cowcollege",emoji:"🎓",title:"Cow College",sub:"Dec 2022 Bronze #1",section:"USACO"},
  {id:"feedcows",emoji:"🌾",title:"Feeding the Cows",sub:"Dec 2022 Bronze #2",section:"USACO"},
  {id:"reverseeng",emoji:"🔧",title:"Reverse Engineering",sub:"Dec 2022 Bronze #3",section:"USACO"},
  {id:"photoshoot",emoji:"📸",title:"Photoshoot",sub:"Open 2022 Bronze #1",section:"USACO"},
  {id:"countliars",emoji:"🤥",title:"Counting Liars",sub:"Open 2022 Bronze #2",section:"USACO"},
  {id:"alchemy",emoji:"⚗️",title:"Alchemy",sub:"Open 2022 Bronze #3",section:"USACO"},
  {id:"sleepclass",emoji:"😴",title:"Sleeping in Class",sub:"Feb 2022 Bronze #1",section:"USACO"},
  {id:"photoshoot2",emoji:"📷",title:"Photoshoot 2",sub:"Feb 2022 Bronze #2",section:"USACO"},
  {id:"blocks",emoji:"🧱",title:"Blocks",sub:"Feb 2022 Bronze #3",section:"USACO"},
  {id:"herdle",emoji:"🟩",title:"Herdle",sub:"Jan 2022 Bronze #1",section:"USACO"},
  {id:"nontrans",emoji:"🎲",title:"Non-Transitive Dice",sub:"Jan 2022 Bronze #2",section:"USACO"},
  {id:"drought",emoji:"🏜️",title:"Drought",sub:"Jan 2022 Bronze #3",section:"USACO"},
  {id:"lonelyphoto",emoji:"📸",title:"Lonely Photo",sub:"Dec 2021 Bronze #1",section:"USACO"},
  {id:"aircond1",emoji:"🌡️",title:"Air Cownditioning",sub:"Dec 2021 Bronze #2",section:"USACO"},
  {id:"walkhome",emoji:"🏠",title:"Walking Home",sub:"Dec 2021 Bronze #3",section:"USACO"},
  {id:"acowdemia1",emoji:"📚",title:"Acowdemia I",sub:"Open 2021 Bronze #1",section:"USACO"},
  {id:"acowdemia2",emoji:"👨‍🔬",title:"Acowdemia II",sub:"Open 2021 Bronze #2",section:"USACO"},
  {id:"acowdemia3",emoji:"🐄",title:"Acowdemia III",sub:"Open 2021 Bronze #3",section:"USACO"},
  {id:"yearcow",emoji:"🐂",title:"Year of the Cow",sub:"Feb 2021 Bronze #1",section:"USACO"},
  {id:"comfycows",emoji:"🐄",title:"Comfortable Cows",sub:"Feb 2021 Bronze #2",section:"USACO"},
  {id:"clockfence",emoji:"🔄",title:"Clockwise Fence",sub:"Feb 2021 Bronze #3",section:"USACO"},
  {id:"uddered",emoji:"🔤",title:"Uddered but not Herd",sub:"Jan 2021 Bronze #1",section:"USACO"},
  {id:"oddphotos",emoji:"📸",title:"Even More Odd Photos",sub:"Jan 2021 Bronze #2",section:"USACO"},
  {id:"stalling",emoji:"🐄",title:"Just Stalling",sub:"Jan 2021 Bronze #3",section:"USACO"},
  {id:"abcs",emoji:"🔢",title:"Do You Know Your ABCs?",sub:"Dec 2020 Bronze #1",section:"USACO"},
  {id:"daisychains",emoji:"🌼",title:"Daisy Chains",sub:"Dec 2020 Bronze #2",section:"USACO"},
  {id:"stuckinrut",emoji:"🐄",title:"Stuck in a Rut",sub:"Dec 2020 Bronze #3",section:"USACO"},
  {id:"socialdist1",emoji:"😷",title:"Social Distancing I",sub:"Open 2020 Bronze #1",section:"USACO"},
  {id:"socialdist2",emoji:"🦠",title:"Social Distancing II",sub:"Open 2020 Bronze #2",section:"USACO"},
  {id:"cowntrace",emoji:"🔍",title:"Cowntact Tracing",sub:"Open 2020 Bronze #3",section:"USACO"},
  {id:"triangles",emoji:"📐",title:"Triangles",sub:"Feb 2020 Bronze #1",section:"USACO"},
  {id:"madscientist",emoji:"🧪",title:"Mad Scientist",sub:"Feb 2020 Bronze #2",section:"USACO"},
  {id:"swapity",emoji:"🔀",title:"Swapity Swap",sub:"Feb 2020 Bronze #3",section:"USACO"},
  {id:"wordproc",emoji:"📝",title:"Word Processor",sub:"Jan 2020 Bronze #1",section:"USACO"},
  {id:"photoshoot20",emoji:"📸",title:"Photoshoot",sub:"Jan 2020 Bronze #2",section:"USACO"},
  {id:"race",emoji:"🏃",title:"Race",sub:"Jan 2020 Bronze #3",section:"USACO"},
  {id:"cowgym",emoji:"🤸",title:"Cow Gymnastics",sub:"Dec 2019 Bronze #1",section:"USACO"},
  {id:"whereami",emoji:"📍",title:"Where Am I?",sub:"Dec 2019 Bronze #2",section:"USACO"},
  {id:"livestock",emoji:"🐄",title:"Livestock Lineup",sub:"Dec 2019 Bronze #3",section:"USACO"},
  {id:"bucketbrigade",emoji:"🪣",title:"Bucket Brigade",sub:"Open 2019 Bronze #1",section:"USACO"},
  {id:"bucketlist",emoji:"📋",title:"Bucket List",sub:"Open 2019 Bronze #2",section:"USACO"},
  {id:"backforth",emoji:"🔁",title:"Back and Forth",sub:"Open 2019 Bronze #3",section:"USACO"},
  {id:"teamwork",emoji:"🤝",title:"Teamwork",sub:"Feb 2019 Bronze #1",section:"USACO"},
  {id:"measurement",emoji:"📏",title:"Measurement",sub:"Feb 2019 Bronze #2",section:"USACO"},
  {id:"sleepy",emoji:"😴",title:"Sleepy Cow Herding",sub:"Feb 2019 Bronze #3",section:"USACO"},
  {id:"convention",emoji:"🎪",title:"Convention",sub:"Jan 2019 Bronze #1",section:"USACO"},
  {id:"moobuzz",emoji:"🔔",title:"Moobuzz",sub:"Jan 2019 Bronze #2",section:"USACO"},
  {id:"lemonade",emoji:"🍋",title:"Lemonade Line",sub:"Jan 2019 Bronze #3",section:"USACO"},
  {id:"billboard",emoji:"🪧",title:"Billboard",sub:"Dec 2018 Bronze #1",section:"USACO"},
  {id:"billboard2",emoji:"🪧",title:"Billboard II",sub:"Dec 2018 Bronze #2",section:"USACO"},
  {id:"moocast",emoji:"📡",title:"Moocast",sub:"Dec 2018 Bronze #3",section:"USACO"},
  {id:"word",emoji:"📖",title:"Word Processor",sub:"Open 2018 Bronze #1",section:"USACO"},
  {id:"whatthemoo",emoji:"🐄",title:"What's Up MooTube",sub:"Open 2018 Bronze #2",section:"USACO"},
  {id:"bovgenomics",emoji:"🧬",title:"Bovine Genomics",sub:"Open 2018 Bronze #3",section:"USACO"},
  {id:"bovshuffle",emoji:"🔀",title:"Bovine Shuffle",sub:"Feb 2018 Bronze #1",section:"USACO"},
  {id:"blockgame",emoji:"🧩",title:"Block Game",sub:"Feb 2018 Bronze #2",section:"USACO"},
  {id:"gymnastics2",emoji:"🤸",title:"Gymnastics",sub:"Feb 2018 Bronze #3",section:"USACO"},
  {id:"lost",emoji:"❓",title:"Lost Cow",sub:"Jan 2018 Bronze #1",section:"USACO"},
  {id:"moomoose",emoji:"🫎",title:"Milk Measurement",sub:"Jan 2018 Bronze #2",section:"USACO"},
  {id:"arboretum",emoji:"🌳",title:"Arboretum",sub:"Jan 2018 Bronze #3",section:"USACO"},
  {id:"circlecross",emoji:"⭕",title:"Circle Cross",sub:"Dec 2017 Bronze #1",section:"USACO"},
  {id:"nocross",emoji:"🚫",title:"No Cross",sub:"Dec 2017 Bronze #2",section:"USACO"},
  {id:"paintbarn",emoji:"🎨",title:"Paint Barn",sub:"Dec 2017 Bronze #3",section:"USACO"},
  {id:"moostacles",emoji:"🏃",title:"Moostacles",sub:"Open 2017 Bronze #1",section:"USACO"},
  {id:"billboards",emoji:"🪧",title:"Billboards",sub:"Open 2017 Bronze #2",section:"USACO"},
  {id:"cowjump",emoji:"🐄",title:"Cow Jumping",sub:"Open 2017 Bronze #3",section:"USACO"},
  {id:"reach",emoji:"🤚",title:"Cow Reach",sub:"Feb 2017 Bronze #1",section:"USACO"},
  {id:"lawnmower",emoji:"🌿",title:"Lawnmower",sub:"Feb 2017 Bronze #2",section:"USACO"},
  {id:"mooyo",emoji:"🎮",title:"Mooyo Mooyo",sub:"Feb 2017 Bronze #3",section:"USACO"},
  {id:"cowdance",emoji:"💃",title:"Cow Dance Show",sub:"Jan 2017 Bronze #1",section:"USACO"},
  {id:"herdingb",emoji:"🐄",title:"Herd Sums",sub:"Jan 2017 Bronze #2",section:"USACO"},
  {id:"considerb",emoji:"🤔",title:"Considerung",sub:"Jan 2017 Bronze #3",section:"USACO"},
  {id:"fencedin",emoji:"🌾",title:"Fenced In",sub:"Dec 2016 Bronze #1",section:"USACO"},
  {id:"lazyb",emoji:"😴",title:"Lazy Cow",sub:"Dec 2016 Bronze #2",section:"USACO"},
  {id:"mooyo2",emoji:"🎮",title:"Moo",sub:"Dec 2016 Bronze #3",section:"USACO"},
  // MCC
  {id:"cat",emoji:"🐱",title:"CAT",sub:"MCC 2024",section:"MCC"},
  {id:"gates",emoji:"🚪",title:"Gates",sub:"MCC 2024",section:"MCC"},
  {id:"factory",emoji:"🏭",title:"Factory",sub:"MCC 2024",section:"MCC"},
  {id:"abcpath",emoji:"🔤",title:"ABC Path",sub:"MCC 2023",section:"MCC"},
  {id:"blockchase",emoji:"🧱",title:"Block Chase",sub:"MCC 2023",section:"MCC"},
  {id:"timebomb",emoji:"💣",title:"Time Bomb",sub:"MCC 2023",section:"MCC"},
  {id:"bribery",emoji:"💰",title:"Bribery",sub:"MCC 2022",section:"MCC"},
  {id:"alchemy2",emoji:"⚗️",title:"Alchemy II",sub:"MCC 2022",section:"MCC"},
  {id:"swapity2",emoji:"🔀",title:"Swapity Swap II",sub:"MCC 2022",section:"MCC"},
]

export const PROBLEM_MAP = new Map(ALL_PROBLEMS.map(p => [p.id, p]))
export const PROBLEM_INDEX = new Map(ALL_PROBLEMS.map((p, i) => [p.id, i]))
