// Shared problem metadata — used by both server (generateStaticParams) and client UI

export interface ProblemMeta {
  id: string
  emoji: string
  title: string
  sub: string
  section: string
  /** 원래 문제 URL (USACO/MCC 등). 없으면 자동으로 Google 검색 fallback 생성. */
  url?: string
}

/** 원래 문제 URL — 명시 안 됐으면 Google 검색 fallback. */
export function getOriginalProblemUrl(p: ProblemMeta): string {
  if (p.url) return p.url
  // 기본 fallback: Google 검색 — site:usaco.org 로 좁혀서 USACO 공식 페이지 우선 노출
  if (p.section === "USACO") {
    return `https://www.google.com/search?q=${encodeURIComponent(`USACO ${p.title} ${p.sub} site:usaco.org`)}`
  }
  // MCC 및 기타: 일반 검색
  return `https://www.google.com/search?q=${encodeURIComponent(`${p.section} ${p.title} ${p.sub}`)}`
}

export const ALL_PROBLEMS: ProblemMeta[] = [
  // USACO
  {id:"rounding",emoji:"🔄",title:"Roundabout Rounding",sub:"Dec 2024 Bronze #1",section:"USACO",url:"https://usaco.org/index.php?page=viewproblem2&cpid=1443"},
  {id:"cheese",emoji:"🧀",title:"Cheese Block",sub:"Dec 2024 Bronze #2",section:"USACO",url:"https://usaco.org/index.php?page=viewproblem2&cpid=1444"},
  {id:"moo",emoji:"🐄",title:"It's Mooin' Time",sub:"Dec 2024 Bronze #3",section:"USACO",url:"https://usaco.org/index.php?page=viewproblem2&cpid=1445"},
  {id:"permutation",emoji:"🔢",title:"FJ's Fav Permutation",sub:"Jan 2025 Bronze #1",section:"USACO",url:"https://usaco.org/index.php?page=viewproblem2&cpid=1421"},
  {id:"interview",emoji:"🐄",title:"Bessie's Interview",sub:"Jan 2025 Bronze #2",section:"USACO"},
  {id:"balanced",emoji:"🔗",title:"Balanced Subsequences",sub:"Jan 2025 Bronze #3",section:"USACO"},
  {id:"checkups",emoji:"🐮",title:"Cow Checkups",sub:"Feb 2025 Bronze #1",section:"USACO",url:"https://usaco.org/index.php?page=viewproblem2&cpid=1469"},
  {id:"exchange",emoji:"🥛",title:"Milk Exchange",sub:"Feb 2025 Bronze #2",section:"USACO",url:"https://usaco.org/index.php?page=viewproblem2&cpid=1396"},
  {id:"presents",emoji:"🎁",title:"Stack of Presents",sub:"Feb 2025 Bronze #3",section:"USACO"},
  {id:"hps",emoji:"✊",title:"HPS Minus One",sub:"Open 2025 Bronze #1",section:"USACO",url:"https://usaco.org/index.php?page=viewproblem2&cpid=1515"},
  {id:"cowphotos",emoji:"📸",title:"More Cow Photos",sub:"Open 2025 Bronze #2",section:"USACO",url:"https://usaco.org/index.php?page=viewproblem2&cpid=1516"},
  {id:"mooin3",emoji:"🐄",title:"Mooin' Time III",sub:"Open 2025 Bronze #3",section:"USACO",url:"https://usaco.org/index.php?page=viewproblem2&cpid=1517"},
  {id:"logicalmoos",emoji:"🧠",title:"Logical Moos",sub:"Open 2024 Bronze #1",section:"USACO",url:"https://usaco.org/index.php?page=viewproblem2&cpid=1419"},
  {id:"walkfence",emoji:"🚶",title:"Walking Along a Fence",sub:"Open 2024 Bronze #2",section:"USACO",url:"https://usaco.org/index.php?page=viewproblem2&cpid=1420"},
  {id:"favperm2",emoji:"🧩",title:"FJ's Fav Perm II",sub:"Open 2024 Bronze #3",section:"USACO",url:"https://usaco.org/index.php?page=viewproblem2&cpid=1421"},
  {id:"palindrome",emoji:"🎲",title:"Palindrome Game",sub:"Feb 2024 Bronze #1",section:"USACO",url:"https://usaco.org/index.php?page=viewproblem2&cpid=1395"},
  {id:"milkexchange",emoji:"🥛",title:"Milk Exchange",sub:"Feb 2024 Bronze #2",section:"USACO",url:"https://usaco.org/index.php?page=viewproblem2&cpid=1396"},
  {id:"productivity",emoji:"📊",title:"Max Productivity",sub:"Feb 2024 Bronze #3",section:"USACO",url:"https://usaco.org/index.php?page=viewproblem2&cpid=1397"},
  {id:"majority",emoji:"🗳️",title:"Majority Opinion",sub:"Jan 2024 Bronze #1",section:"USACO",url:"https://usaco.org/index.php?page=viewproblem2&cpid=1371"},
  {id:"cannonball",emoji:"💥",title:"Cannonball",sub:"Jan 2024 Bronze #2",section:"USACO",url:"https://usaco.org/index.php?page=viewproblem2&cpid=1372"},
  {id:"bacteria",emoji:"🦠",title:"Balancing Bacteria",sub:"Jan 2024 Bronze #3",section:"USACO",url:"https://usaco.org/index.php?page=viewproblem2&cpid=1373"},
  {id:"candycane",emoji:"🍬",title:"Candy Cane Feast",sub:"Dec 2023 Bronze #1",section:"USACO",url:"https://usaco.org/index.php?page=viewproblem2&cpid=1347"},
  {id:"cowntact",emoji:"🦠",title:"Cowntact Tracing 2",sub:"Dec 2023 Bronze #2",section:"USACO",url:"https://usaco.org/index.php?page=viewproblem2&cpid=1348"},
  {id:"fjfarms",emoji:"🌱",title:"FJ Actually Farms",sub:"Dec 2023 Bronze #3",section:"USACO",url:"https://usaco.org/index.php?page=viewproblem2&cpid=1349"},
  {id:"feb23",emoji:"🔤",title:"FEB",sub:"Open 2023 Bronze #1",section:"USACO",url:"https://usaco.org/index.php?page=viewproblem2&cpid=1323"},
  {id:"moolang",emoji:"📝",title:"Moo Language",sub:"Open 2023 Bronze #2",section:"USACO",url:"https://usaco.org/index.php?page=viewproblem2&cpid=1324"},
  {id:"rotshift",emoji:"🔄",title:"Rotate and Shift",sub:"Open 2023 Bronze #3",section:"USACO",url:"https://usaco.org/index.php?page=viewproblem2&cpid=1325"},
  {id:"hungrycow",emoji:"🐄",title:"Hungry Cow",sub:"Feb 2023 Bronze #1",section:"USACO",url:"https://usaco.org/index.php?page=viewproblem2&cpid=1299"},
  {id:"stampgrid",emoji:"📮",title:"Stamp Grid",sub:"Feb 2023 Bronze #2",section:"USACO",url:"https://usaco.org/index.php?page=viewproblem2&cpid=1300"},
  {id:"mooloo",emoji:"📺",title:"Watching Mooloo",sub:"Feb 2023 Bronze #3",section:"USACO",url:"https://usaco.org/index.php?page=viewproblem2&cpid=1301"},
  {id:"leaders",emoji:"👑",title:"Leaders",sub:"Jan 2023 Bronze #1",section:"USACO",url:"https://usaco.org/index.php?page=viewproblem2&cpid=1275"},
  {id:"aircond",emoji:"❄️",title:"Air Cownditioning II",sub:"Jan 2023 Bronze #2",section:"USACO",url:"https://usaco.org/index.php?page=viewproblem2&cpid=1276"},
  {id:"mooops",emoji:"🐮",title:"Moo Operations",sub:"Jan 2023 Bronze #3",section:"USACO",url:"https://usaco.org/index.php?page=viewproblem2&cpid=1277"},
  {id:"cowcollege",emoji:"🎓",title:"Cow College",sub:"Dec 2022 Bronze #1",section:"USACO",url:"https://usaco.org/index.php?page=viewproblem2&cpid=1251"},
  {id:"feedcows",emoji:"🌾",title:"Feeding the Cows",sub:"Dec 2022 Bronze #2",section:"USACO",url:"https://usaco.org/index.php?page=viewproblem2&cpid=1252"},
  {id:"reverseeng",emoji:"🔧",title:"Reverse Engineering",sub:"Dec 2022 Bronze #3",section:"USACO",url:"https://usaco.org/index.php?page=viewproblem2&cpid=1253"},
  {id:"photoshoot",emoji:"📸",title:"Photoshoot",sub:"Open 2022 Bronze #1",section:"USACO",url:"https://usaco.org/index.php?page=viewproblem2&cpid=1227"},
  {id:"countliars",emoji:"🤥",title:"Counting Liars",sub:"Open 2022 Bronze #2",section:"USACO",url:"https://usaco.org/index.php?page=viewproblem2&cpid=1228"},
  {id:"alchemy",emoji:"⚗️",title:"Alchemy",sub:"Open 2022 Bronze #3",section:"USACO",url:"https://usaco.org/index.php?page=viewproblem2&cpid=1229"},
  {id:"sleepclass",emoji:"😴",title:"Sleeping in Class",sub:"Feb 2022 Bronze #1",section:"USACO",url:"https://usaco.org/index.php?page=viewproblem2&cpid=1203"},
  {id:"photoshoot2",emoji:"📷",title:"Photoshoot 2",sub:"Feb 2022 Bronze #2",section:"USACO",url:"https://usaco.org/index.php?page=viewproblem2&cpid=1204"},
  {id:"blocks",emoji:"🧱",title:"Blocks",sub:"Feb 2022 Bronze #3",section:"USACO",url:"https://usaco.org/index.php?page=viewproblem2&cpid=1205"},
  {id:"herdle",emoji:"🟩",title:"Herdle",sub:"Jan 2022 Bronze #1",section:"USACO",url:"https://usaco.org/index.php?page=viewproblem2&cpid=1179"},
  {id:"nontrans",emoji:"🎲",title:"Non-Transitive Dice",sub:"Jan 2022 Bronze #2",section:"USACO",url:"https://usaco.org/index.php?page=viewproblem2&cpid=1180"},
  {id:"drought",emoji:"🏜️",title:"Drought",sub:"Jan 2022 Bronze #3",section:"USACO",url:"https://usaco.org/index.php?page=viewproblem2&cpid=1181"},
  {id:"lonelyphoto",emoji:"📸",title:"Lonely Photo",sub:"Dec 2021 Bronze #1",section:"USACO",url:"https://usaco.org/index.php?page=viewproblem2&cpid=1155"},
  {id:"aircond1",emoji:"🌡️",title:"Air Cownditioning",sub:"Dec 2021 Bronze #2",section:"USACO",url:"https://usaco.org/index.php?page=viewproblem2&cpid=1156"},
  {id:"walkhome",emoji:"🏠",title:"Walking Home",sub:"Dec 2021 Bronze #3",section:"USACO",url:"https://usaco.org/index.php?page=viewproblem2&cpid=1157"},
  {id:"acowdemia1",emoji:"📚",title:"Acowdemia I",sub:"Open 2021 Bronze #1",section:"USACO",url:"https://usaco.org/index.php?page=viewproblem2&cpid=1131"},
  {id:"acowdemia2",emoji:"👨‍🔬",title:"Acowdemia II",sub:"Open 2021 Bronze #2",section:"USACO",url:"https://usaco.org/index.php?page=viewproblem2&cpid=1132"},
  {id:"acowdemia3",emoji:"🐄",title:"Acowdemia III",sub:"Open 2021 Bronze #3",section:"USACO",url:"https://usaco.org/index.php?page=viewproblem2&cpid=1133"},
  {id:"yearcow",emoji:"🐂",title:"Year of the Cow",sub:"Feb 2021 Bronze #1",section:"USACO",url:"https://usaco.org/index.php?page=viewproblem2&cpid=1107"},
  {id:"comfycows",emoji:"🐄",title:"Comfortable Cows",sub:"Feb 2021 Bronze #2",section:"USACO",url:"https://usaco.org/index.php?page=viewproblem2&cpid=1108"},
  {id:"clockfence",emoji:"🔄",title:"Clockwise Fence",sub:"Feb 2021 Bronze #3",section:"USACO",url:"https://usaco.org/index.php?page=viewproblem2&cpid=1109"},
  {id:"uddered",emoji:"🔤",title:"Uddered but not Herd",sub:"Jan 2021 Bronze #1",section:"USACO",url:"https://usaco.org/index.php?page=viewproblem2&cpid=1083"},
  {id:"oddphotos",emoji:"📸",title:"Even More Odd Photos",sub:"Jan 2021 Bronze #2",section:"USACO",url:"https://usaco.org/index.php?page=viewproblem2&cpid=1084"},
  {id:"stalling",emoji:"🐄",title:"Just Stalling",sub:"Jan 2021 Bronze #3",section:"USACO",url:"https://usaco.org/index.php?page=viewproblem2&cpid=1085"},
  {id:"abcs",emoji:"🔢",title:"Do You Know Your ABCs?",sub:"Dec 2020 Bronze #1",section:"USACO",url:"https://usaco.org/index.php?page=viewproblem2&cpid=1059"},
  {id:"daisychains",emoji:"🌼",title:"Daisy Chains",sub:"Dec 2020 Bronze #2",section:"USACO",url:"https://usaco.org/index.php?page=viewproblem2&cpid=1060"},
  {id:"stuckinrut",emoji:"🐄",title:"Stuck in a Rut",sub:"Dec 2020 Bronze #3",section:"USACO",url:"https://usaco.org/index.php?page=viewproblem2&cpid=1061"},
  {id:"socialdist1",emoji:"😷",title:"Social Distancing I",sub:"Open 2020 Bronze #1",section:"USACO",url:"https://usaco.org/index.php?page=viewproblem2&cpid=1035"},
  {id:"socialdist2",emoji:"🦠",title:"Social Distancing II",sub:"Open 2020 Bronze #2",section:"USACO",url:"https://usaco.org/index.php?page=viewproblem2&cpid=1036"},
  {id:"cowntrace",emoji:"🔍",title:"Cowntact Tracing",sub:"Open 2020 Bronze #3",section:"USACO",url:"https://usaco.org/index.php?page=viewproblem2&cpid=1037"},
  {id:"triangles",emoji:"📐",title:"Triangles",sub:"Feb 2020 Bronze #1",section:"USACO",url:"https://usaco.org/index.php?page=viewproblem2&cpid=1011"},
  {id:"madscientist",emoji:"🧪",title:"Mad Scientist",sub:"Feb 2020 Bronze #2",section:"USACO",url:"https://usaco.org/index.php?page=viewproblem2&cpid=1012"},
  {id:"swapity",emoji:"🔀",title:"Swapity Swap",sub:"Feb 2020 Bronze #3",section:"USACO",url:"https://usaco.org/index.php?page=viewproblem2&cpid=1013"},
  {id:"wordproc",emoji:"📝",title:"Word Processor",sub:"Jan 2020 Bronze #1",section:"USACO",url:"https://usaco.org/index.php?page=viewproblem2&cpid=987"},
  {id:"photoshoot20",emoji:"📸",title:"Photoshoot",sub:"Jan 2020 Bronze #2",section:"USACO",url:"https://usaco.org/index.php?page=viewproblem2&cpid=988"},
  {id:"race",emoji:"🏃",title:"Race",sub:"Jan 2020 Bronze #3",section:"USACO",url:"https://usaco.org/index.php?page=viewproblem2&cpid=989"},
  {id:"cowgym",emoji:"🤸",title:"Cow Gymnastics",sub:"Dec 2019 Bronze #1",section:"USACO",url:"https://usaco.org/index.php?page=viewproblem2&cpid=963"},
  {id:"whereami",emoji:"📍",title:"Where Am I?",sub:"Dec 2019 Bronze #2",section:"USACO",url:"https://usaco.org/index.php?page=viewproblem2&cpid=964"},
  {id:"livestock",emoji:"🐄",title:"Livestock Lineup",sub:"Dec 2019 Bronze #3",section:"USACO",url:"https://usaco.org/index.php?page=viewproblem2&cpid=965"},
  {id:"bucketbrigade",emoji:"🪣",title:"Bucket Brigade",sub:"Open 2019 Bronze #1",section:"USACO",url:"https://usaco.org/index.php?page=viewproblem2&cpid=939"},
  {id:"milkfactory",emoji:"🏭",title:"Milk Factory",sub:"Open 2019 Bronze #2",section:"USACO",url:"https://usaco.org/index.php?page=viewproblem2&cpid=940"},
  {id:"cowevolution",emoji:"🧬",title:"Cow Evolution",sub:"Open 2019 Bronze #3",section:"USACO",url:"https://usaco.org/index.php?page=viewproblem2&cpid=941"},
  {id:"sleepyherd",emoji:"😴",title:"Sleepy Cow Herding",sub:"Feb 2019 Bronze #1",section:"USACO",url:"https://usaco.org/index.php?page=viewproblem2&cpid=915"},
  {id:"revegetation",emoji:"🌱",title:"Great Revegetation",sub:"Feb 2019 Bronze #2",section:"USACO",url:"https://usaco.org/index.php?page=viewproblem2&cpid=916"},
  {id:"meastraffic",emoji:"🚗",title:"Measuring Traffic",sub:"Feb 2019 Bronze #3",section:"USACO",url:"https://usaco.org/index.php?page=viewproblem2&cpid=917"},
  {id:"shellgame",emoji:"🐚",title:"Shell Game",sub:"Jan 2019 Bronze #1",section:"USACO",url:"https://usaco.org/index.php?page=viewproblem2&cpid=891"},
  {id:"sleepysort",emoji:"😴",title:"Sleepy Cow Sorting",sub:"Jan 2019 Bronze #2",section:"USACO",url:"https://usaco.org/index.php?page=viewproblem2&cpid=892"},
  {id:"guessanimal",emoji:"🐾",title:"Guess the Animal",sub:"Jan 2019 Bronze #3",section:"USACO",url:"https://usaco.org/index.php?page=viewproblem2&cpid=893"},
  {id:"mixmilk",emoji:"🥛",title:"Mixing Milk",sub:"Dec 2018 Bronze #1",section:"USACO",url:"https://usaco.org/index.php?page=viewproblem2&cpid=855"},
  {id:"bucketlist",emoji:"🪣",title:"The Bucket List",sub:"Dec 2018 Bronze #2",section:"USACO",url:"https://usaco.org/index.php?page=viewproblem2&cpid=856"},
  {id:"backforth",emoji:"🔄",title:"Back and Forth",sub:"Dec 2018 Bronze #3",section:"USACO",url:"https://usaco.org/index.php?page=viewproblem2&cpid=857"},
  {id:"teamttt",emoji:"❌",title:"Team Tic Tac Toe",sub:"Open 2018 Bronze #1",section:"USACO",url:"https://usaco.org/index.php?page=viewproblem2&cpid=831"},
  {id:"milkorder",emoji:"🐄",title:"Milking Order",sub:"Open 2018 Bronze #2",section:"USACO",url:"https://usaco.org/index.php?page=viewproblem2&cpid=832"},
  {id:"familytree",emoji:"🌳",title:"Family Tree",sub:"Open 2018 Bronze #3",section:"USACO",url:"https://usaco.org/index.php?page=viewproblem2&cpid=833"},
  {id:"teleport",emoji:"🌀",title:"Teleportation",sub:"Feb 2018 Bronze #1",section:"USACO",url:"https://usaco.org/index.php?page=viewproblem2&cpid=807"},
  {id:"hoofball",emoji:"⚽",title:"Hoofball",sub:"Feb 2018 Bronze #2",section:"USACO",url:"https://usaco.org/index.php?page=viewproblem2&cpid=808"},
  {id:"tameherd",emoji:"🐄",title:"Taming the Herd",sub:"Feb 2018 Bronze #3",section:"USACO",url:"https://usaco.org/index.php?page=viewproblem2&cpid=809"},
  {id:"billboard2",emoji:"🪧",title:"Blocked Billboard II",sub:"Jan 2018 Bronze #1",section:"USACO",url:"https://usaco.org/index.php?page=viewproblem2&cpid=783"},
  {id:"lifeguards",emoji:"🏊",title:"Lifeguards",sub:"Jan 2018 Bronze #2",section:"USACO",url:"https://usaco.org/index.php?page=viewproblem2&cpid=784"},
  {id:"outofplace",emoji:"🔀",title:"Out of Place",sub:"Jan 2018 Bronze #3",section:"USACO",url:"https://usaco.org/index.php?page=viewproblem2&cpid=785"},
  {id:"billboard",emoji:"🪧",title:"Blocked Billboard",sub:"Dec 2017 Bronze #1",section:"USACO",url:"https://usaco.org/index.php?page=viewproblem2&cpid=759"},
  {id:"bovshuffle",emoji:"🔀",title:"The Bovine Shuffle",sub:"Dec 2017 Bronze #2",section:"USACO",url:"https://usaco.org/index.php?page=viewproblem2&cpid=760"},
  {id:"milkmeas",emoji:"📊",title:"Milk Measurement",sub:"Dec 2017 Bronze #3",section:"USACO",url:"https://usaco.org/index.php?page=viewproblem2&cpid=761"},
  {id:"lostcow",emoji:"🐄",title:"The Lost Cow",sub:"Open 2017 Bronze #1",section:"USACO",url:"https://usaco.org/index.php?page=viewproblem2&cpid=735"},
  {id:"bovgenomics",emoji:"🧬",title:"Bovine Genomics",sub:"Open 2017 Bronze #2",section:"USACO",url:"https://usaco.org/index.php?page=viewproblem2&cpid=736"},
  {id:"modernart",emoji:"🎨",title:"Modern Art",sub:"Open 2017 Bronze #3",section:"USACO",url:"https://usaco.org/index.php?page=viewproblem2&cpid=737"},
  {id:"crossroad1",emoji:"🐄",title:"Cross the Road",sub:"Feb 2017 Bronze #1",section:"USACO",url:"https://usaco.org/index.php?page=viewproblem2&cpid=711"},
  {id:"crossroad2",emoji:"🔀",title:"Cross the Road II",sub:"Feb 2017 Bronze #2",section:"USACO",url:"https://usaco.org/index.php?page=viewproblem2&cpid=712"},
  {id:"crossroad3",emoji:"🚪",title:"Cross the Road III",sub:"Feb 2017 Bronze #3",section:"USACO",url:"https://usaco.org/index.php?page=viewproblem2&cpid=713"},
  {id:"dontbelast",emoji:"🥛",title:"Don't Be Last!",sub:"Jan 2017 Bronze #1",section:"USACO",url:"https://usaco.org/index.php?page=viewproblem2&cpid=687"},
  {id:"hps17",emoji:"✊",title:"Hoof Paper Scissors",sub:"Jan 2017 Bronze #2",section:"USACO",url:"https://usaco.org/index.php?page=viewproblem2&cpid=688"},
  {id:"cowtipping",emoji:"🐄",title:"Cow Tipping",sub:"Jan 2017 Bronze #3",section:"USACO",url:"https://usaco.org/index.php?page=viewproblem2&cpid=689"},
  {id:"sqpasture",emoji:"⬜",title:"Square Pasture",sub:"Dec 2016 Bronze #1",section:"USACO",url:"https://usaco.org/index.php?page=viewproblem2&cpid=663"},
  {id:"blockgame",emoji:"🧊",title:"Block Game",sub:"Dec 2016 Bronze #2",section:"USACO",url:"https://usaco.org/index.php?page=viewproblem2&cpid=664"},
  {id:"cowsignal",emoji:"📡",title:"The Cow-Signal",sub:"Dec 2016 Bronze #3",section:"USACO",url:"https://usaco.org/index.php?page=viewproblem2&cpid=665"},
  // MCC
  {id:"fences",emoji:"🏗️",title:"Building Fences",sub:"MCC 2025 P1",section:"MCC"},
  {id:"fans",emoji:"🪭",title:"Fans",sub:"MCC 2025 P2",section:"MCC"},
  {id:"tricks",emoji:"🎃",title:"Trick or Treat",sub:"MCC 2025 P3",section:"MCC"},
  {id:"word",emoji:"📝",title:"Word Distance",sub:"MCC 2025 P4",section:"MCC"},
  {id:"reach",emoji:"🐉",title:"Reachability Queries",sub:"MCC 2025 P5",section:"MCC"},
  {id:"subseqmedian",emoji:"📊",title:"Subseq Median Sum",sub:"MCC 2025 P6",section:"MCC"},
  {id:"cornercover",emoji:"📐",title:"Corner Cover",sub:"MCC 2024 P1",section:"MCC"},
  {id:"gifts",emoji:"🎁",title:"Gifts",sub:"MCC 2024 P2",section:"MCC"},
  {id:"magicorbs",emoji:"🔮",title:"Magical Orbs",sub:"MCC 2024 P3",section:"MCC"},
  {id:"simplegame",emoji:"🎮",title:"Simple Game",sub:"MCC 2024 P4",section:"MCC"},
  {id:"explodingarrow",emoji:"💥",title:"Exploding Arrow",sub:"MCC 2024 P5",section:"MCC"},
  {id:"xorstring",emoji:"⊕",title:"XOR The String",sub:"MCC 2024 P6",section:"MCC"},
  {id:"collatz",emoji:"🔢",title:"Collatz",sub:"MCC 2023 P1",section:"MCC"},
  {id:"mobilegame",emoji:"📱",title:"Mobile Game",sub:"MCC 2023 P2",section:"MCC"},
  {id:"innovation",emoji:"💡",title:"Innovation",sub:"MCC 2023 P3",section:"MCC"},
  {id:"tichu",emoji:"🃏",title:"Tichu",sub:"MCC 2023 P4",section:"MCC"},
  {id:"rectangles",emoji:"▬",title:"Rectangles",sub:"MCC 2023 P5",section:"MCC"},
  {id:"sumk",emoji:"∑",title:"Sum^K",sub:"MCC 2023 P6",section:"MCC"},
  {id:"mcc19rect",emoji:"📏",title:"Rectangle",sub:"MCC 2019 P1",section:"MCC"},
  {id:"mcc19bakery",emoji:"🥖",title:"Bakery",sub:"MCC 2019 P2",section:"MCC"},
  {id:"mcc19candy",emoji:"🍬",title:"Candy",sub:"MCC 2019 P3",section:"MCC"},
  {id:"mcc19ditcoin",emoji:"💰",title:"Ditcoin",sub:"MCC 2019 P4",section:"MCC"},
  {id:"mcc19elim",emoji:"🔢",title:"Elimination",sub:"MCC 2019 P5",section:"MCC"},
  {id:"mcc19palindrome",emoji:"🔄",title:"Palindrome",sub:"MCC 2019 P6",section:"MCC"},
  {id:"mcc19rect2",emoji:"▭",title:"Rectangle 2",sub:"MCC 2019 P7",section:"MCC"},
  {id:"mcc15rect",emoji:"▭",title:"Rectangle",sub:"MCC 2015 P1",section:"MCC"},
  {id:"mcc15equation",emoji:"➕",title:"Complete the Equation",sub:"MCC 2015 P2",section:"MCC"},
  {id:"mcc15bahasaf",emoji:"🗣️",title:"Bahasa F",sub:"MCC 2015 P3",section:"MCC"},
  {id:"mcc15isthmus",emoji:"⛰️",title:"Isthmus",sub:"MCC 2015 P4",section:"MCC"},
  {id:"mcc15choco",emoji:"🍫",title:"Chocolate Bars",sub:"MCC 2015 P5",section:"MCC"},
  {id:"mcc22grammar",emoji:"📖",title:"Grammar",sub:"MCC 2022 P1",section:"MCC"},
  {id:"mcc22aliens",emoji:"👽",title:"Aliens",sub:"MCC 2022 P2",section:"MCC"},
  {id:"mcc22maze",emoji:"🏰",title:"Maze",sub:"MCC 2022 P3",section:"MCC"},
  {id:"mcc22birthday",emoji:"🎂",title:"Cats' Birthday",sub:"MCC 2022 P4",section:"MCC"},
  {id:"mcc22cardshark",emoji:"🃏",title:"Card Shark",sub:"MCC 2022 P5",section:"MCC"},
  {id:"mcc22lamp",emoji:"💡",title:"Lamp",sub:"MCC 2022 P6",section:"MCC"},
  {id:"mcc21carrots",emoji:"🥕",title:"Carrots",sub:"MCC 2021 P1",section:"MCC"},
  {id:"mcc21dvd",emoji:"📀",title:"DVD Screensaver",sub:"MCC 2021 P2",section:"MCC"},
  {id:"mcc21marbles",emoji:"🔴",title:"Marbles and Boxes",sub:"MCC 2021 P3",section:"MCC"},
  {id:"mcc21glass",emoji:"🥛",title:"Round Glass",sub:"MCC 2021 P4",section:"MCC"},
  {id:"mcc21simplemath",emoji:"🔢",title:"Simple Math",sub:"MCC 2021 P5",section:"MCC"},
  {id:"mcc21menu",emoji:"📋",title:"Smallest Menu Ever",sub:"MCC 2021 P6",section:"MCC"},
  {id:"mcc20cipher",emoji:"🔐",title:"Cipher",sub:"MCC 2020 P1",section:"MCC"},
  {id:"mcc20citytour",emoji:"🏙️",title:"City Tour",sub:"MCC 2020 P2",section:"MCC"},
  {id:"mcc20kitty",emoji:"🐱",title:"Kitty Numbers",sub:"MCC 2020 P3",section:"MCC"},
  {id:"mcc20knight",emoji:"♞",title:"Knight",sub:"MCC 2020 P4",section:"MCC"},
  {id:"mcc20missing",emoji:"❓",title:"Missing Number",sub:"MCC 2020 P5",section:"MCC"},
  {id:"mcc20zigzag",emoji:"⚡",title:"Zig-zag",sub:"MCC 2020 P6",section:"MCC"},
  // MCO
  {id:"mco15badminton",emoji:"🏸",title:"Badminton",sub:"MCO 2015 P1",section:"MCO"},
  {id:"mco15honey",emoji:"🍯",title:"Honey",sub:"MCO 2015 P2",section:"MCO"},
  {id:"mco15bitcoin",emoji:"₿",title:"Bitcoin",sub:"MCO 2015 P3",section:"MCO"},
  {id:"mco15trains",emoji:"🚂",title:"Trains",sub:"MCO 2015 P4",section:"MCO"},
  {id:"mco15secret",emoji:"🔐",title:"Secret",sub:"MCO 2015 P5",section:"MCO"},
]

export const PROBLEM_MAP = new Map(ALL_PROBLEMS.map(p => [p.id, p]))
export const PROBLEM_INDEX = new Map(ALL_PROBLEMS.map((p, i) => [p.id, i]))
