/* 영어 주석 → 한국어. `codeCommentsKo.ts` 가 합쳐 쓴다. 3/4 (2026-09-21) */
export const PART3: Record<string, string> = {
  "'L' run ahead of cow i": "cow i 바로 앞에 이어지는 'L' 무리",
  "(b) ★ moved in → no new ★": "(b) 별이 들어옴 → 새 별 안 생김",
  "-1 = still moving (Infinity)": "-1 = 아직 멈추는 중 (무한대)",
  "0-indexed beauty grid": "0부터 시작하는 beauty 격자",
  "1) every cow with milk passes 1L to its L/R neighbor":
    "1) 우유 있는 소는 모두 왼쪽/오른쪽 이웃에게 1L 을 건네요",
  "2) any cow over its cap loses the overflow": "2) 한도를 넘은 소는 넘친 만큼 잃어요",
  "4) total = total - before + after": "4) total = total - before + after",
  "= (3*n - (n mod 2)) / 2": "= (3*n - (n mod 2)) / 2",
  "A +1/-1 range command changes the total gap by at most 2, so the":
    "구간에 +1 이나 -1 을 더하는 명령 한 번은 전체 차이를 최대 2 만큼 바꿔요. 그래서",
  "All cows must be used, so leftover cows pile onto the": "소는 전부 어딘가에 들어가야 해서, 남는 소는",
  "Answer = total milk - sum of those losses.": "답 = 전체 우유 - 잃은 양의 합이에요.",
  "Bessie's start time = when her counter becomes free": "베시의 시작 시간 = 베시가 쓸 카운터가 빌 때예요",
  "Build basic sentences, popping words from the back of each list.":
    "기본 문장을 만들어요. 각 리스트 뒤에서부터 단어를 하나씩 꺼내요.",
  "Case 1: target[k] sits later in s[0]. One swap fixes it.":
    "경우 1: target[k] 가 s[0] 뒤쪽에 있어요. 교환 한 번이면 돼요.",
  "Count checkups after reversing cow[l..r]": "cow[l..r] 을 뒤집은 뒤 검진 횟수를 세요",
  "DP on this path": "이 경로에서 DP 를 해요",
  "E cow arrives": "동쪽 소가 도착해요",
  "Each AC is on or off, so with M <= 10 there are at most 1024 combinations.":
    "에어컨은 각각 켜짐/꺼짐 둘 중 하나라서, M <= 10 이면 조합이 최대 1024 가지예요.",
  "Fill the table from home (bottom-right) BACKWARD — no recursion.":
    "집(오른쪽 아래)에서부터 거꾸로 표를 채워요 — 재귀 없이요.",
  "First cell of the path — nothing came from before": "경로의 첫 칸이에요 — 이전에서 온 게 없어요",
  "Flip last char if s[i+2] != 'O': cost 1": "s[i+2] 가 'O' 가 아니면 마지막 글자를 바꿔요: 비용 1",
  "G cell → star existed but disappeared": "G 칸 → 별이 있었는데 사라졌어요",
  "Greedy peel: a group of rows can become one if-statement only":
    "탐욕적으로 벗겨내기: 행 묶음이 if문 하나가 될 수 있는 건",
  "H beats S, P beats H, S beats P → cow1 wins if (a, b) ∈ {(H,S), (P,H), (S,P)}":
    "H 는 S 를 이기고, P 는 H 를 이기고, S 는 P 를 이겨요 → (a, b) 가 {(H,S), (P,H), (S,P)} 중 하나면 cow1 이 이겨요",
  "Initial milk equals each cow's capacity": "처음 우유량은 각 소의 한도와 같아요",
  "K must stay in [-3N, 3N]": "K 는 [-3N, 3N] 범위 안에 있어야 해요",
  "Middle char must be 'O' (can't flip middle)": "가운데 글자는 반드시 'O' 여야 해요 (가운데는 못 바꿔요)",
  "Move right": "오른쪽으로 이동",
  "N cow arrives later -> N cow stops": "북쪽 소가 더 늦게 도착 -> 북쪽 소가 멈춰요",
  "O(N³) per query": "O(N³) per query",
  "Optimized: sort and use prefix sums": "최적화: 정렬하고 누적합을 써요",
  "Pass 1: count GREEN (exact match), record leftover breeds":
    "1차 훑기: GREEN(정확히 일치) 개수를 세고, 남은 종류를 기록해요",
  "Process the TALLEST cow first: she has the fewest stalls that fit.":
    "키가 제일 큰 소부터 처리해요: 맞는 축사가 제일 적으니까요.",
  "Resolve collisions in time order.": "충돌을 시간 순서대로 처리해요.",
  "Simulate again tracking start times": "시작 시간을 추적하면서 다시 시뮬레이션해요",
  "Special case: stars don't move": "특별한 경우: 별이 움직이지 않아요",
  "Step 2: read s as a binary number n, mod MOD.": "2단계: s 를 이진수 n 으로 읽어요, MOD 로 나눈 나머지로요.",
  "Step B: swap column k between s_1 and s_y.": "B단계: s_1 과 s_y 사이에서 k 열을 바꿔요.",
  "TO-DO list (instead of recursion)": "할 일 목록 (재귀 대신)",
  "The new cow + her 4 neighbors are the only cells": "새로 온 소와 그 이웃 4칸만",
  "Those are the ones Bessie could have gone to": "그게 바로 베시가 갈 수 있었던 카운터들이에요",
  "Try each position i as start of 'MOO'": "'MOO' 의 시작 자리로 각 위치 i 를 다 시도해요",
  "Try to find target[k] later in s[0] -> 1 op suffices.":
    "s[0] 뒤쪽에서 target[k] 를 찾아봐요 -> 한 번이면 충분해요.",
  "Two non-transitive cycle directions are both valid:": "비이행 순환 방향은 둘 다 가능해요:",
  "W cell → no star": "W 칸 → 별 없음",
  "Walk right to left. Track parity of O's typed later.":
    "오른쪽에서 왼쪽으로 가요. 나중에 입력한 O 개수의 홀짝을 추적해요.",
  "We want as many Guernseys (G) in even 1-indexed":
    "짝수 번째(1부터 셀 때) 자리에 Guernsey(G) 를 최대한 많이 두고 싶어요",
  "X beats Y when more (x, y) pairs have x > y than x < y":
    "(x, y) 쌍 중 x > y 인 게 x < y 인 것보다 많으면 X 가 Y 를 이겨요",
  "add new bales": "새 건초를 더해요",
  "all same output -> one if": "출력이 다 같으면 -> if문 하나",
  "and read a number's digits in base 2: digit j says 'is AC j on?'":
    "그 수를 2진수로 읽어요: j번째 자리가 'j번 에어컨이 켜졌나?' 를 말해줘요",
  "are all numbers in target[start:end) the same?": "target[start:end) 안의 수가 전부 같나요?",
  "ascending": "오름차순",
  "beauty[r][c] = current beauty of cow at (r,c). 0-indexed.":
    "beauty[r][c] = (r,c) 자리 소의 현재 값이에요. 0부터 시작해요.",
  "both H: nothing helps this pair": "둘 다 H 면: 이 쌍은 도와줄 게 없어요",
  "cannot reach further right": "더 오른쪽으로 못 가요",
  "cnt[i]     = how many copies of i exist → must REMOVE": "cnt[i] = i 가 몇 개나 있는지예요 → 없애야 해요",
  "column nx (nx > ex) and the N cow reaches row ey (ey > ny).":
    "nx 열 (nx > ex) 이고, 북쪽 소가 ey 행 (ey > ny) 에 도착할 때예요.",
  "copy: a failed attempt must not eat stock": "복사본이에요: 실패한 시도가 재고를 축내면 안 돼요",
  "count papers with >= h citations": "인용 수가 h 이상인 논문 개수를 세요",
  "cow grows": "소가 자라요",
  "cum[i] = total distance walked from post 0 to post i (along the boundary)":
    "cum[i] = 말뚝 0 에서 말뚝 i 까지 (테두리를 따라) 걸은 총 거리예요",
  "day 0 (1-indexed day 1): counter = 0, breakouts = 1": "day 0 (1-인덱스로는 day 1): counter = 0, breakouts = 1",
  "depth = 1: mother, 2: grand-mother, 3: great-grand-mother, ...":
    "depth = 1: 엄마, 2: 할머니, 3: 증조할머니, ...",
  "direction string of 'L'/'R'": "'L'/'R' 로 된 방향 문자열",
  "distance 2": "거리 2",
  "dots per column": "열마다 있는 풀 개수",
  "each even group needs a filler: 1 even OR 2 leftover odds":
    "짝수 묶음마다 채울 게 필요해요: 짝수 소 1마리 또는 남는 홀수 소 2마리",
  "even N: alternating sum must be 0": "N 이 짝수면: 번갈아 더하고 뺀 합이 0이어야 해요",
  "every occupied cell": "채워진 칸 전부",
  "have one ready — use it": "이미 준비된 게 있으면 — 그걸 써요",
  "heights, one line": "키, 한 줄로",
  "integer sqrt": "정수 제곱근",
  "known radii, largest first": "알려진 반지름, 큰 것부터",
  "leave opponent in a losing state": "상대를 지는 상태로 남겨요",
  "leftover odds must come in pairs.": "남는 홀수 소는 짝을 지어야 해요.",
  "max(0, r-K+1) <= i <= min(r, W-1),  same for j": "max(0, r-K+1) <= i <= min(r, W-1) (j 도 마찬가지예요)",
  "min-heap of (free_time, counter_id)": "(free_time, counter_id) 의 최소 힙이에요",
  "minimum number of commands equals the sum of |d[i]-d[i+1]| over the":
    "최소 명령 개수는 |d[i]-d[i+1]| 의 합과 같아요. 이 배열은",
  "more zeros than we can delete": "지울 수 있는 것보다 0 이 더 많아요",
  "need last h papers": "마지막 h 개 논문이 필요해요",
  "no breakout: c → c+1": "탈출 없음: c → c+1",
  "number of test cases": "테스트 케이스 개수",
  "one reversal brings the G over": "한 번 뒤집으면 G 가 넘어와요",
  "only the first time we pop it": "처음 꺼낼 때만이에요",
  "p[i] = target temp": "p[i] = 원하는 온도예요",
  "perm[pos] = block assigned to letter w[pos]": "perm[pos] = w[pos] 글자에 배정된 블록이에요",
  "points in current game": "지금 게임의 점수",
  "positions 1,3,5... need even sum": "1,3,5... 번째 자리는 합이 짝수여야 해요",
  "pub[y] has less effort => pub[y] is senior to pub[x]": "pub[y] 의 노력이 더 적어요 => pub[y] 가 pub[x] 보다 선배예요",
  "reached home": "집에 도착",
  "right = opposite-breed cows touching i on the right": "right = 오른쪽에서 i 에 붙어 있는 다른 품종 소의 수예요",
  "sequence+budget -> one string key": "수열+budget 을 문자열 키 하나로 만들어요",
  "smallest first": "작은 것부터",
  "solve case (next steps)": "케이스를 풀어요 (다음 단계)",
  "string of A/B": "A/B 로 된 문자열",
  "t[i] = current temp": "t[i] = 지금 온도예요",
  "the 5-window at position k": "k 위치에서의 5칸짜리 창이에요",
  "the later cow (gets stopped)": "더 늦게 도착한 소 (멈추는 쪽)",
  "they trade milk forever and each leaks 1L every minute. Behind":
    "이 둘은 우유를 영원히 주고받고, 1분마다 1L 씩 새어 나가요. 그 뒤로는",
  "trick 2": "요령 2",
  "trick 3": "요령 3",
  "undo the +K": "+K 를 되돌려요",
  "value i-1 is absent → one more missing": "i-1 값이 없어요 → 빠진 게 하나 더 늘어요",
  "when the LATER cow reaches the meeting cell": "더 늦게 도착한 소가 만나는 칸에 닿을 때예요",
  "whose comfort status can change this step.": "이번에 편안한지 아닌지가 바뀔 수 있는 칸이에요.",
  "y-direction row: (x, z)": "y-방향 줄: (x, z)",
  "⊕ XOR": "⊕ XOR",
  "✋ BASE CASE — recursion stops here!": "✋ 베이스 케이스 — 여기서 재귀가 멈춰요!",
};
