/* 영어 주석 → 한국어. `codeCommentsKo.ts` 가 합쳐 쓴다. 1/4 (2026-09-21) */
export const PART1: Record<string, string> = {
  "'.' = no patch, else 'G'/'H'": "'.' 은 조각이 없다는 뜻이고, 아니면 'G' 나 'H' 예요",
  "'or' starts a new chain": "'or' 는 새로운 사슬을 시작해요",
  "(nx > ex) and N reaches row ey (ey > ny).": "(nx > ex) 이고, N 소는 ey 행에 다다라야 해요 (ey > ny).",
  "... + same for x-direction and y-direction": "… 그리고 x방향, y방향도 똑같이 해요",
  "1) A beats B, B beats C, C beats A": "1) A가 B를 이기고, B가 C를 이기고, C가 A를 이겨요",
  "2) B beats A, C beats B, A beats C": "2) B가 A를 이기고, C가 B를 이기고, A가 C를 이겨요",
  "2+ on right, none on left": "오른쪽엔 2개 이상, 왼쪽엔 0개",
  "8 integers per test case: 4 faces of A, then 4 faces of B": "테스트케이스마다 정수 8개: A의 면 4개, 그다음 B의 면 4개",
  "A 'deficit pair' is two adjacent cows S[i]=='R', S[i+1]=='L':": "'손해 짝' 은 이웃한 소 두 마리가 S[i]=='R', S[i+1]=='L' 인 경우예요:",
  "AC: range, power, cost": "에어컨: 범위, 세기, 비용",
  "All cows that could give same result as Bessie": "베시와 같은 결과를 낼 수 있는 소들 전부",
  "BFS using list as queue": "리스트를 큐로 쓰는 BFS",
  "Brute force every die C (4 faces, values 1-10, sorted to skip dupes)": "주사위 C 를 다 해봐요 (면 4개, 값 1~10, 중복을 건너뛰려고 정렬)",
  "Can `w` be spelled? Try every assignment of distinct blocks to letters.": "`w` 를 만들 수 있나요? 서로 다른 블록을 글자에 배정하는 모든 경우를 해봐요.",
  "Check all counters with min finish time": "끝나는 시간이 가장 빠른 카운터를 다 확인해요",
  "Count plants strictly TALLER than i.": "i 보다 확실히 더 큰 식물의 개수를 세요.",
  "Delete chars before i: cost = i": "i 앞의 글자를 지워요: 비용 = i",
  "E cow arrives later -> E cow stops": "E 소가 늦게 도착하면 -> E 소가 멈춰요",
  "Each cell tells us directly:": "각 칸이 바로 알려주는 것:",
  "Find Bessie's start time": "베시의 출발 시각을 찾아요",
  "Fix s[0] one position at a time, left to right.": "s[0] 을 왼쪽부터 오른쪽으로 한 자리씩 정해요.",
  "For each position p, count contradictions": "자리 p 마다 모순이 몇 개인지 세요",
  "G — two cases": "G — 경우가 두 가지예요",
  "Groups alternate: even-sum, odd-sum, even-sum, ...": "그룹이 번갈아요: 합이 짝수, 합이 홀수, 합이 짝수, ...",
  "How many stalls have limit >= this cow's height?": "이 소의 키보다 한도가 크거나 같은 칸은 몇 개인가요?",
  "Inverse map: at[p] = cow currently at position p": "거꾸로 된 표: at[p] = 지금 자리 p 에 있는 소",
  "Look ahead inside s_1 first: 1 op only.": "먼저 s_1 안을 미리 봐요: 연산 1번만.",
  "Minimum moves": "최소로 움직이는 횟수",
  "N cow arrives": "N 소가 도착해요",
  "Number of merges = N - (total // target)": "합치는 횟수 = N - (total // target)",
  "Only a North cow and an East cow can ever collide.": "북쪽으로 가는 소와 동쪽으로 가는 소만 부딪힐 수 있어요.",
  "Output: at each position p, which cow is there.": "출력: 자리 p 마다 어떤 소가 있는지예요.",
  "Peel such groups off until none remain (OK) or stuck (LIE).": "그런 그룹을 하나씩 떼어내요. 다 없어지면(OK) 성공, 더는 못 떼면(LIE) 실패예요.",
  "Recompute free times just before Bessie arrives": "베시가 도착하기 바로 전에 비는 시간을 다시 계산해요",
  "S[i][j] = sum of K x K window with top-left (i,j)": "S[i][j] = 왼쪽 위가 (i,j) 인 K x K 칸의 합",
  "Sort cows DESCENDING, stalls ASCENDING.": "소는 내림차순으로, 칸은 오름차순으로 정렬해요.",
  "Step 1: if any digit is not 0/1, binarize (costs 1 op).": "1단계: 0이나 1이 아닌 숫자가 있으면 0/1로 바꿔요 (연산 1번).",
  "Step 3: g(n) = floor(3*n / 2)": "3단계: g(n) = floor(3*n / 2)",
  "Swap column k between s_1 and s_y.": "s_1 과 s_y 사이에서 k번째 열을 바꿔요.",
  "Tallest cow first: she fits in the fewest stalls.": "키가 제일 큰 소부터예요: 들어갈 수 있는 칸이 제일 적거든요.",
  "They can meet at cell (nx, ey) only if the E cow reaches": "E 소가 다다라야만 (nx, ey) 칸에서 만날 수 있어요",
  "Try each day x from 0 upward — bound 1100 is enough under Bronze constraints.": "0부터 하루씩 늘려가며 x 를 시도해요 — Bronze 제약에서는 1100까지면 충분해요.",
  "Try every possible die C: 4 faces, values 1..10 (sorted to skip duplicates)": "가능한 주사위 C 를 다 시도해요: 면 4개, 값 1~10 (중복을 건너뛰려고 정렬)",
  "Try to partition into segments summing to target": "합이 target 이 되는 구간들로 나눠봐요",
  "Values are guaranteed in [0, N], so an array of size N+1 is enough.": "값은 [0, N] 안에 있다고 보장되니, 크기 N+1 인 배열이면 충분해요.",
  "Walk one star path": "별 하나의 경로를 따라가요",
  "Walk the target order left to right. A cow must be moved": "목표 순서를 왼쪽에서 오른쪽으로 따라가요. 소는 옮겨야 해요",
  "We will read each S inside the loop below.": "아래 반복문 안에서 S 를 하나씩 읽을 거예요.",
  "a cow that should come after it in target": "목표에서는 자기보다 뒤에 와야 하는 소",
  "ahead). That chain pours its milk into the loop and never gets it": "ahead 있는 소들). 그 사슬은 자기 우유를 고리 안으로 흘려보내고 다시는",
  "already a G in the even slot": "짝수 자리에 이미 G 가 있어요",
  "answer = (sum of |d[i]-d[i+1]| over the padded array) / 2.": "answer = (패딩된 배열에서 |d[i]-d[i+1]| 을 다 더한 값) / 2.",
  "array padded with 0 on BOTH ends, divided by 2.": "양쪽 끝에 0을 채운 배열이고, 2로 나눠요.",
  "at most 2 ** 10 = 1024 combinations. Number them 0, 1, 2, ...": "많아야 2 ** 10 = 1024가지 조합이에요. 0, 1, 2, ... 로 번호를 매겨요",
  "binary string, output digit": "이진 문자열, 출력할 숫자",
  "can = the front desk: not in the notebook? ask solve, write it down": "can = 접수처예요: 장부에 없으면 solve 에게 물어보고 적어둬요",
  "cells that currently have exactly 3 neighbors": "지금 이웃이 정확히 3개인 칸들",
  "coefficient: 1, 2, 4, ...": "계수: 1, 2, 4, ...",
  "cooling at each stall": "칸마다 필요한 냉방",
  "count ONES, not window length": "창문 길이가 아니라 1 의 개수를 세요",
  "covers up to (i+K)+K": "(i+K)+K 까지 덮어요",
  "craft each ingredient": "재료를 하나씩 만들어요",
  "d[i] = how much stall i must change (target - current)": "d[i] = 칸 i 가 얼마나 바뀌어야 하는지 (target - current)",
  "decreasing effort order": "노력이 큰 순서부터 작은 순서로",
  "descending": "내림차순으로",
  "direction: 0 = arrived moving right, 1 = arrived moving down, 2 = start": "방향: 0 = 오른쪽으로 움직이며 도착, 1 = 아래로 움직이며 도착, 2 = 시작",
  "does a block of block_len repeat all the way?": "길이가 block_len 인 덩어리가 끝까지 반복되나요?",
  "dp[r][c][direction][changes] = # of ways from (r, c) to home (N-1, N-1)": "dp[r][c][direction][changes] = (r, c) 에서 집 (N-1, N-1) 까지 가는 방법의 수",
  "eat remaining after last delivery until day T": "마지막 배달 이후부터 T 일까지 남은 걸 먹어요",
  "even N: f is free, so push the even-indexed o[] down by their minimum": "N 이 짝수일 때: f 는 자유로우니, 짝수 번째 o[] 를 그 최솟값만큼 내려요",
  "games won": "이긴 경기 수",
  "have[i] = units of metal i (1-indexed)": "have[i] = 금속 i 의 개수 (1번부터 시작)",
  "i taller cows already used i of those stalls": "더 큰 소 i 마리가 그 칸 중 i 개를 이미 썼어요",
  "intransitive sentences as fit, then combine pairs with conjunctions.": "자동사 문장은 될 만큼 넣고, 그다음 짝을 접속사로 합쳐요.",
  "last group (extra evens keep parity; extra odds in pairs).": "마지막 그룹이에요 (남는 짝수는 그대로 두고, 남는 홀수는 짝을 지어요).",
  "left if its current position sits before one we've": "지금 있는 자리가 이미 정한 자리보다 앞이면 왼쪽으로 옮겨요",
  "leftover odds pair up": "남은 홀수끼리 짝을 지어요",
  "memo = the answer notebook = memoization": "memo = 답을 적어두는 장부, 메모이제이션이에요",
  "min_stars[0] = min stars so far, when this cell does NOT pass a star out": "min_stars[0] = 이 칸이 별을 밖으로 안 보낼 때, 지금까지 최소 별 개수",
  "missing[i] = number of v in {0, 1, ..., i-1} where cnt[v] == 0.": "missing[i] = {0, 1, ..., i-1} 중에서 cnt[v] == 0 인 v 의 개수예요.",
  "must be a positive perfect square": "양수인 완전제곱수여야 해요",
  "next_permutation walks all orderings of {0,1,2,3} — no recursion.": "next_permutation 이 {0,1,2,3} 의 모든 순서를 다 돌아요 — 재귀 없이요.",
  "no stock, no recipe": "재고도 없고 레시피도 없어요",
  "odd N: final value f must be >= 0": "N 이 홀수일 때: 최종 값 f 는 0 이상이어야 해요",
  "ones currently inside the window": "지금 창문 안에 있는 1 의 개수",
  "ops = max(missing[i], cnt[i])": "ops = max(missing[i], cnt[i])",
  "parent[child] = mother": "parent[child] = 엄마",
  "place as far right as possible": "될 수 있는 대로 오른쪽에 놓아요",
  "pos[cow] = index of that cow in the current line": "pos[cow] = 지금 줄에서 그 소가 있는 자리",
  "positions 2,4,6... need odd sum": "2,4,6... 번째 자리는 합이 홀수여야 해요",
  "query is 'V S' — V first, then S": "질문은 'V S' 예요 — V 가 먼저, 그다음 S",
  "real effort gap (not just a tie)": "진짜 노력 차이예요 (단순히 동점이 아니라)",
  "senior[i][j] = i is DEFINITELY more senior than j": "senior[i][j] = i 가 j 보다 확실히 선배예요",
  "skip duplicate K": "중복된 K 는 건너뛰어요",
  "so we take the MAX of the two (not sum).": "그래서 둘 중 큰 값을 써요 (더하지 않고요).",
  "stall range, cooling needed": "칸의 범위, 필요한 냉방",
  "such chain pours its milk into the loop and never gets it back,": "그런 사슬은 자기 우유를 고리 안으로 흘려보내고 다시 돌려받지 못해요,",
  "that orientation for everything further left.": "그보다 왼쪽에 있는 건 모두 방향이 뒤집혀요.",
  "the earlier cow": "더 먼저 온 소",
  "they call each other -> declare": "서로를 부르니까 -> 미리 선언해요",
  "trailing 0 pad (needed when d ends negative)": "끝에 0을 채워요 (d 가 음수로 끝날 때 필요해요)",
  "trick 2: how many candidates checked": "요령 2: 후보를 몇 개나 확인했는지예요",
  "trick 3: cut in two and split the budget": "요령 3: 둘로 나눠서 예산을 나눠요",
  "used[1..4]": "used[1..4]",
  "walk the 'L' run ahead of cow i": "소 i 앞에 있는 'L' 뭉치를 따라가요",
  "which cow of a pair lands in the even slot, and flips": "짝에서 어느 소가 짝수 자리에 들어가는지 정해지고, 뒤집혀요",
  "worst case: merge all into one": "최악의 경우예요: 다 하나로 합쳐요",
  "zeros currently inside the window": "지금 창문 안에 있는 0 의 개수",
  "─── helpers (no recursion — checks & slicing) ───": "─── 도우미 함수들 (재귀 없이 — 확인과 자르기) ───",
};
